### ISSUE TITLE
pn_message_set_format doesn't exist from Qpid Proton C 0.9.1

### ISSUE THREAD

**Issue by ppatierno** [Azure/azure-event-hubs#1]
Hi,
I tried to compile the send.sln using Qpid Proton C 0.9.1 (or 0.10) and the result is that it can't compile because starting from 0.9.1 version the function pn_message_set_format was removed.
It is used in the eventhubclient_II.c.
I started from a PC with Qpid Proton already built (the 0.9.1 version and the current 0.10 version from GitHub official repository). I didn't use your build_proton (on Windows) however I see that it download last 0.10 version from repository.
The solution can be compiled only using Qpid Proton C up to 0.8 version where the above function was still present but considered "deprecated".

However what kind of format is trying to apply the library code ?

else if (pn_message_set_format(eventHubClientLLStruct->message, 0x80013700) != 0)
    {
        result = EVENTHUBCLIENT_ERROR;
        LogError("pn_message_set_format failed.\r\n");
    }

I see that without the above code, the pn_messanger_status returns PN_STATUS_ABORTED.

Thanks,
Paolo

**Comment by jebrando** [comment]
Our implementation uses a forked version proton-c 0.9.  We forked this to support the Microsoft format that allows the batching of message to the EventHub endpoint.  The supported code can be found here: https://github.com/dcristoloveanu/qpid-proton.git.

**Comment by ppatierno** [comment]
Sorry ... I didn't see these following lines in the build__proton : 

set proton-repo=https://github.com/dcristoloveanu/qpid-proton.git
set proton-branch=0.9-IoTClient

However, downloading the original 0.9 version from Qpid Proton web site and your fork I can't find the pn_message_set_format in the message.c file. I can see only references to the binding for Ruby and Python but not code about pn_message_set_format for C implementation.

If I use your fork ... I can't compile ... always same error

from Compiler ...

Warning	C4013	'pn_message_set_format' undefined; assuming extern returning int	eventhubclient	C:\Users\ppati\Source\Repos\azure-event-hubs\c\eventhub_client\src\eventhubclient_ll.c	582

from Linker ...

LNK2019	unresolved external symbol _pn_message_set_format referenced in function _GenerateMessagePayload	send	C:\Users\ppati\Source\Repos\azure-event-hubs\c\eventhub_client\samples\send\windows\eventhubclient.lib(eventhubclient_ll.obj)	1

Paolo

**Comment by jebrando** [comment]
Usually that message means you have a older proton in the path somewhere.  You should use the remove_proton.sh script to remove the proton path.  Then you can search your path for the qpid-proton library on your system.
