### ISSUE TITLE
Not able to receive any messages after a while.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs#105]
client.receive() calls start returning NULL after a while although new messages are available on the stream partition.

**Comment by SreeramGarlapati** [comment]
We identified the root cause in the amqp library that we depend on (proton-j) - https://issues.apache.org/jira/browse/PROTON-1171
Pull Request with fix: https://github.com/apache/qpid-proton/pull/73

**Comment by SreeramGarlapati** [comment]
proton-j released 0.12.2 to fix this issue. we released 0.6.7 which pulls this version of proton-j.
Thanks @serkantkaraca for reporting the issue.
