### ISSUE TITLE
Support for Event Hub in Go

### ISSUE THREAD

**Issue by simonwistow** [Azure/azure-event-hubs#113]
It'd be great to be able to get support for Event Hubs (or at least a util library for generating SAS Authorization headers easily)..

**Comment by jtaubensee** [comment]
@salameer and @simonwistow - We do not have any immediate plans to support Go. But we can leave this issue open for a while to see if there are others looking for support as well.

**Comment by jtjk** [comment]
Hi,

This is not done by Microsoft? https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/eventhub#NewEventHubsClient

**Comment by jtaubensee** [comment]
@jtjk - The library you are referencing is for Azure Resource Management, and will allow you to provision Event Hubs namespaces, etc, but does not provide run-time operations.

**Comment by koalalorenzo** [comment]
Any update? We would like to use Go to manage, send and listen on Event Hub.
Is this something that is going to happen?

**Comment by zhongyi-zhang** [comment]
+1 to the request. I hope to use GO, too.

**Comment by xinyiou** [comment]
It looks like there is a GitHub project around this: https://github.com/openenergi/go-event-hub

**Comment by sabeegrewal** [comment]
Hey everyone, we'll be fully supporting golang within the month. The code will be hosted here: https://github.com/azure/azure-event-hubs-go. Please open an issue there if any further support is needed!
