### ISSUE TITLE
High-throughput "single sender" client scenarios apparently not supported

### ISSUE THREAD

**Issue by bojingo** [Azure/azure-event-hubs#114]
I attempted to convert an IoT GatewayServer, written in Java, from writing to an Azure Storage Queue to write to an Event Hub.  However, after swapping the implementation of the "queue writer" class to use the EventHubClient to write the messages, the performance was absolutely abysmal.  Using our device simulator we used to get about 40K message per half hour with the Azure Storage Queue (which is far below the 250K message benchmark we see in production, but the device simulator has been our bottleneck), but that number dropped to about 3K message with the EventHubClient.

It appears one limiting factor is that the Java version does not have an equivalent to this API from the .NET library: https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.messagingfactory.createeventhubclient.aspx

As stated in the .NET library docs: https://github.com/Azure/azure-content/blob/master/articles/event-hubs/event-hubs-programming-guide.md#create-an-event-hubs-client
_________________
It is important to note that additional EventHubClient objects created from a messaging factory instance will reuse the same underlying TCP connection. Therefore, these objects have a client-side limit on throughput. The Create method reuses a single messaging factory. If you need very high throughput from a single sender, then you can create multiple message factories and one EventHubClient object from each messaging factory.
_________________

Sure enough, the Java library creates EventHubClient objects as singletons, but there is no way to create them from different MessagingFactory instances as far as I can tell.

However, I think the performance issues go way beyond that.  We have downstream .NET processes right now that write to Event Hubs without making use of that API, or even without making use of SendBatch (because we use partition keys and batches by partition key wouldn't buy us much) and are achieving throughput of hundreds of thousands of messages per hour with little effort.

**Comment by SreeramGarlapati** [comment]
I am not very sure about IoT GwServer & device simulator.

1. what is events/sec you are trying to send & avg. message size.
[we have customers using eventhubs java client and sending **500 messages per sec **of a 100 bytes msg on a single EventHubClient instance (one physical socket). which is - 500*60*30 for half hour]

2. Regarding the API difference between JavaClient & .net Client: we tried to simplify the API. In JavaClient API - 1 EventHubClient instance has exactly one socket opened with EventHubs Service. If you need more connections create more EventHubClient's. EventHubClient is not Singleton - you can create as many as you need.

Also, make sure to move to the current latest version **0.6.6**.

**Comment by bojingo** [comment]
1. Target would be about 250,000 messages per half hour, which comes to 138 messages per second, averaging maybe 500 bytes per message.  Achieved performance was 1.67 messages per second.
2. I'll look again, but that is not what we were seeing.  In any case, I tried doing this where each thread had its own EventHubClient reference returned from EventHubClient.createFromConnectionStringSync and was getting NullPointerExceptions on each attempt to send.  NullPointerException was thrown in MessagingFactory's RunReactor.run method, though I don't have a full stack trace to post at the moment.

We were using 0.6.4 (was latest when we started this effort).  We will upgrade, try again, and post back the results.

**Comment by SreeramGarlapati** [comment]
Also, when you try with the latest version - if you experience huge deviation from what is expected - pls. be sure to provide your repro code snippet... Thx!

**Comment by wofr** [comment]
This basically fits to my observation #112.  
As I said I writting an scala application using akka-streams where the event-hub-client gives me back-pressure in the sense that I allow only a amount of  X (e.g. 500) send futures pending.

I did a test-run where I could deliver 1 000 000 elements within 5 min. This means 1 000 000 futures completed successfully in a very short time. But after a certain time the rate drops and reaches zeor.
At this point not even one send returns succesfully.

**Comment by bojingo** [comment]
It seems version 0.6.4 was the culprit.  The below simple code shows the performance difference using different methods.  I added timings in comments above the different methods.  The performance improvements upgrading to 0.6.6 were very dramatic.

Note that there seem to be issues with thread-safety.  Not sure if that is known/expected, but I didn't easily see documentation indicating whether it should be thread-safe.  In any case, I updated my implementation in the actual system to do all the writing on a dedicated thread and I'm getting the throughput performance and reliability that I expected.  

```
import com.microsoft.azure.eventhubs.EventData;
import com.microsoft.azure.eventhubs.EventHubClient;
import com.microsoft.azure.servicebus.ServiceBusException;

import java.io.UnsupportedEncodingException;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.stream.*;

public class Main {
    private static final String CONNECTION_STRING = "";
    private static final int MESSAGE_COUNT = 10;
    private static final int THREAD_COUNT = 5;
    private static List<EventData> eventData;

    public static void main(String[] args) {
        try {
            eventData = generateData();

            roundRobinMultipleEventHubClients();
            //simple();
            //simpleParallelFor();
            //simpleTwoThreads();
            //simpleAsync();
            //batch();

        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    // 37920
    // 41067
    // AFTER UPGRADE TO 0.6.6
    // 3332
    // 3139
    private static void roundRobinMultipleEventHubClients() {
        try {
            EventHubClient[] clients = new EventHubClient[10];
            for(int i = 0; i < clients.length; i++) {
                clients[i] = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            }
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            for (int i = 0; i < eventData.size(); i++) {
                clients[i % clients.length].sendSync(eventData.get(i));
            }
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    // 39585
    // 36418
    // AFTER UPGRADE TO 0.6.6
    // 1609
    // 1659
    private static void simple() {
        try {
            EventHubClient client = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            for (int i = 0; i < eventData.size(); i++) {
                client.sendSync(eventData.get(i));
            }
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    // NullPointerException:
    // Caused by: java.lang.NullPointerException
    //   at com.microsoft.azure.eventhubs.EventHubClient.send(EventHubClient.java:183)
    //   at com.microsoft.azure.eventhubs.EventHubClient.sendSync(EventHubClient.java:123)
    // AFTER UPGRADE TO 0.6.6
    // Random NullPointerExceptions persist
    private static void simpleParallelFor() {
        try {
            EventHubClient client = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            Stream<EventData> stream = eventData.parallelStream();
            stream.forEach((data) -> {
                uncheckedSendSync(client, data);
            });
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    // 16277
    // 10447
    // RANDOMLY:
    // NullPointerException:
    // Caused by: java.lang.NullPointerException
    //   at com.microsoft.azure.eventhubs.EventHubClient.send(EventHubClient.java:183)
    //   at com.microsoft.azure.eventhubs.EventHubClient.sendSync(EventHubClient.java:123)
    // AFTER UPGRADE TO 0.6.6
    // Random NullPointerExceptions persist (about 95% of the time)
    // 1353
    // 948
    private static void simpleTwoThreads() {
        try {
            EventHubClient client = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            Mod2EventSendSync odd = new Mod2EventSendSync(client, 1);
            Mod2EventSendSync even = new Mod2EventSendSync(client, 0);
            odd.start();
            even.start();
            odd.join();
            even.join();
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    // 7111
    // 9513
    // AFTER UPGRADE TO 0.6.6
    // 535
    // 476
    private static void simpleAsync() {
        try {
            EventHubClient client = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            List<CompletableFuture<Void>> sendFutures = new LinkedList<>();
            for (int i = 0; i < eventData.size(); i++) {
                sendFutures.add(client.send(eventData.get(i)));
            }
            for (int i = 0; i < sendFutures.size(); i++) {
                sendFutures.get(i).get();
            }
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    // 6516
    // 6481
    // AFTER UPGRADE TO 0.6.6
    // 417
    // 251
    private static void batch() {
        try {
            EventHubClient client = EventHubClient.createFromConnectionStringSync(CONNECTION_STRING);
            LocalDateTime start = LocalDateTime.now();
            System.out.println("Started: " + start);
            client.sendSync(eventData);
            LocalDateTime stop = LocalDateTime.now();
            System.out.println("Stopped: " + stop + "  -  Elapsed milliseconds: " + ChronoUnit.MILLIS.between(start, stop));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void uncheckedSendSync(EventHubClient client, EventData data) {
        try {
            client.sendSync(data);
        } catch (ServiceBusException e) {
            throw new RuntimeException(e);
       }
    }

    private static List<EventData> generateData() throws UnsupportedEncodingException {
        List<EventData> eventData = new ArrayList<>();
        for (int i = 0; i < MESSAGE_COUNT; i++) {
            String dataMessage = "Message " + i + " being sent...";
            byte[] data = dataMessage.getBytes("UTF-8");
            eventData.add(new EventData(data));
        }
        return eventData;
    }

    static class Mod2EventSendSync extends Thread {
        private EventHubClient client;
        private int mod2Value;

        public Mod2EventSendSync(EventHubClient client, int mod2Value) {
            this.client = client;
            this.mod2Value = mod2Value;
        }

        @Override
        public void run() {
            for (int i = 0; i < eventData.size(); i++) {
                if (i % 2 == mod2Value) {
                    uncheckedSendSync(client, eventData.get(i));
                }
            }
        }
    }
}
```

**Comment by SreeramGarlapati** [comment]
@bojingo, thanks a lot for taking the extra effort to validate that the high-thruput send scenario - issue is fixed in 0.6.6.
Am closing this issue - as the HighThruput send is clear.

Following up the Thread safety issue as part of: #116 
Thanks a lot for the Repro - I am able to repro and find the problem. I will update you with the fix by EOD 4/19 PST.

**Comment by SreeramGarlapati** [comment]
HI @bojingo ,

Here's a library that I put together, which wrap's around EventHubClient to delivery high-thruput Send. I would appreciate if you can use this and provide feedback.

```
import com.microsoft.azure.eventhubs.extensions.batchSend.BatchSender;

EventHubClient ehClient = EventHubClient.createFromConnectionString(connStr.toString()).get();
BatchSender sender = BatchSender.create(ehClient);
........
sender.send(sendEvent);

<repository> 
<id>azure eventhubs</id> 
<url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1288/</url> 
</repository> 

<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-eventhubs-extensions</artifactId>
<version>0.1.0</version>
</dependency>
```

**Comment by aloysiustany** [comment]
@SreeramGarlapati Asking a .net eventhub library question here hoping you have some information: [MessagingFactory is available in java client](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.eventhubs._messaging_factory) but it is not available in .net library. Do you know if there is an alternate way I can try to reuse the underlying TCP connection when creating eventhub client ?
