### ISSUE TITLE
JavaClient: Request to create Event Hub Client using existing Shared Access Signature token

### ISSUE THREAD

**Issue by jbrodeur** [Azure/azure-event-hubs#119]
JAVA - Event Hub Client Example:

final String namespaceName = "----ServiceBusNamespaceName-----";
final String eventHubName = "----EventHubName-----";
**final String sasToken = "-----SharedAccessSignature token-----";** // A previously issued Shared Access Signature token

ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, **sasToken**);

EventHubClient ehClient = EventHubClient.createFromConnectionString(connStr.toString()).get();

**Comment by SreeramGarlapati** [comment]
Thanks @jbrodeur for suggesting the feature. We are working on it. Will update - as soon as I have an ETA.

**Comment by SreeramGarlapati** [comment]
#15

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#12
