### ISSUE TITLE
Use of these libraries on server side Java are danger

### ISSUE THREAD

**Issue by yoshioterada** [Azure/azure-event-hubs#124]
In order to use these libraries on server side Java with more safety,
please add the support of JSR-236 of Concurrency utilities for Java EE ?
https://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/package-summary.html

Note : 
Until, Java EE 6(not only EE but also simple Servlet environment)
it was not recommended to create the new Thread on server side.
Because the new created Thread is not managed by Java EE container 
(both Servlet container and EJB container). 
As a result, there is a possibility to occur some trouble.

Please refer to the following documents which I explained at JavaOne?
The new created Thread is not proxy object but simple Java Thread Object.
http://www.slideshare.net/OracleMiddleJP/javaone-2013-san-francisco-asynconcurrencyonee7

For example, following code is good for Java SE environment,
but it is not good on server side.
https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs/src/main/java/com/microsoft/azure/servicebus/Timer.java
---

private static final ScheduledThreadPoolExecutor executor 
      = new ScheduledThreadPoolExecutor(Math.max(Runtime.getRuntime().availableProcessors(), 4));
executor.schedule(runnable, seconds, TimeUnit.SECONDS);

For example, we will implement like follows on Java EE 7 environment.
---

public class MyManagedScheduledExecutorService{
 @Resource(name = "concurrent/
             DefaultManagedScheduledExecutorService")
 ManagedScheduledExecutorService managedScheduledExecsvc;

 public void execScheduledExecutorService() {
   MyRunnableTask task = new MyRunnableTask();
   managedScheduledExecsvc.schedule(
      task, 60L, TimeUnit.SECONDS);
 }
---

And I think that there is a problem on following code too.
---

https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/PartitionSender.java
    private CompletableFuture<Void> createInternalSender() throws ServiceBusException
    {
        return MessageSender.create(this.factory, StringUtil.getRandomString(), 
                String.format("%s/Partitions/%s", this.eventHubName, this.partitionId))
                .thenAcceptAsync(new Consumer<MessageSender>()
                {
                    public void accept(MessageSender a) { PartitionSender.this.internalSender = a;}
                });
    }
---

From Java SE 8 API point of view, 
you didn't pass the Executor to the "thenAcceptAsync" of CompletableFuture method.
As a result, it will be unmanaged(danger) code on Java EE environment.

I recommend you to use the following API.
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html
Java SE8 Env : 
thenAcceptAsync(Consumer<? super T> action);
Java SE8/EE7 Env : 
thenAcceptAsync(Consumer<? super T> action, Executor executor);

For example, it will be wrote like following code.
@Resource(name = "concurrent/DefaultManagedExecutorService")
ManagedExecutorService managedExecsvc;

CompletableFuture<Void> tasks = CompletableFuture
    .supplyAsync(execMyAsyncTask1(i), managedExecsvc)
    .thenAccept(System.out::println, managedExecsvc);

I think that these libraries is very good for send/receive the data to Event Hub.
However I will not be able to use these libraries on Java server side environment.
It means that we can't use these lib on Java Web Application.

**Comment by SreeramGarlapati** [comment]
@yoshioterada - that's quite informative. will try to address this by 5/3.

**Comment by yoshioterada** [comment]
Thank you so much SreeramGarlapati-san.

Please review not only my specified point but also 
all of other classes too? Because I didn't review all of the class. 
I assume that there may be a lot of modification point.

I think that it may be difficult to get the instance of ManagedExecutorService or ManagedScheduledExecutorService on libraries side.
So I think that it is useful for developer to get the instance by themselves 
and pass it to the libraries like follows.

Developers code may be as follows.
*******************************************************
// Depedency Injection to get the Resource by developers
@Resource(name = "concurrent/DefaultManagedExecutorService")
ManagedExecutorService managedExecsvc;
// Depedency Injection to get the Resource by developers
@Resource(name = "concurrent/DefaultManagedScheduledExecutorService")
ManagedScheduledExecutorService managedScheduledExecsvc;

// developers will path the instance to libraries method like this.
    public void foo() {
        try {
            byte[] payloadBytes = inputData.getBytes("UTF-8");
            EventData sendEvent = new EventData(payloadBytes);
            //Java SE Environment
            EventHubClient ehClient = 
                  EventHubClient.createFromConnectionString(ENDPOINT).get();
            // Java EE Environment
            EventHubClient ehClient = 
                  EventHubClient.createFromConnectionString(ENDPOINT, **managedExecsvc**).get();
            // Java SE Environment
            PartitionSender sender = ehClient.createPartitionSender("0").get();
            // Java EE Environment
            PartitionSender sender = ehClient.createPartitionSender("0", **managedExecsvc**).get();
            // Java SE Environment
            sender.send(sendEvent).get();
            // Java EE Environment
            sender.send(sendEvent, **managedExecsvc**).get();
            ehClient.close();
            System.out.println(Instant.now() + ": Send Complete... :" + inputData);
        } catch (ServiceBusException | InterruptedException | ExecutionException | IOException e) {
            Logger.getLogger(EventHubBackingBean.class.getName()).log(Level.SEVERE, null, e);
        }
    }

I hope you refer to the  following API.
http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#11
