### ISSUE TITLE
NodeJS: Node client should support some form of auto-retry for transient error

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#13]
Looking through the code in develop branch it looks like we have not formally defined a good strategy for retry on transient error - something similar to the one we have in .Net. I think this is something that should be in the client layer (not in the Amqp layer). We are doing something similar in Java client so NodeJS should have the same behavior for feature parity.

Thanks

**Comment by noodlefrenzy** [comment]
This makes sense to me. Do you have a link to the Java code that does retry? Are you thinking randomized exponential backoff or some other strategy?

**Comment by hmlam** [comment]
We are currently at design phase for the retry logic in the java client (@ https://github.com/Azure/azure-event-hubs/tree/javaClient) so no code yet. The current thinking is just to port the current functional logic from .Net to java (i.e. exponential backoff with some time-staggering build in). I think for NodeJS something similar is fine:

- a simple randomized exponential backoff
- only retry for known transient type AMQP error code (since we have not form of exception struct here).

**Comment by hmlam** [comment]
I talked with our dev writing the Java API today and looks like he actually had a working code in the JavaClient branch for the retry policy, which you can take a look at @ https://github.com/Azure/azure-event-hubs/blob/javaClient/java/src/main/java/com/microsoft/azure/servicebus/RetryExponential.java

Let me know if you have questions on this.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#7
