### ISSUE TITLE
Creating multiple PartitionReceiver's on a Single EventHubClient doesn't work.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs#130]
Below programming approach doesn't work currently.

1. Create one EventHubClient.
2. Try to create all PartitionReceivers from the single client. CreateReceiver call might get stuck and won't complete.
3. If all receivers created fine in the previous step, Reiceve() calls on the PartitionReceivers start returning NULL although there are events to receive.

1 to 1 approach doesn't show this issue though, i.e. "all PartitionReceivers on dedicated EventHubClients" works just fine.

**Comment by SreeramGarlapati** [comment]
We narrowed this down to an issue in the dependent Amqp library - https://issues.apache.org/jira/browse/PROTON-1185.

**Comment by SreeramGarlapati** [comment]
Please verify if 0.7.7 fixed this.

**Comment by serkantkaraca** [comment]
Confirmed the fix on 0.7.7. Thx!

**Comment by SreeramGarlapati** [comment]
same issue as #170
