### ISSUE TITLE
Pulsing read with PartionReceiver callback? [Java-Client 0.6.9]

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#145]
Hi!

I use the EventHub client also to-do a recovery of my state of the application. I read all data form the beginning until the "end".   
For me the “end” is if I receive for a certain amount of time no new data. In my test I wait 15 sec. If I not receive any data I assume I reached the end. Unfortunately my tests sometimes fails and sometimes not.  After some debugging I found that sometimes I got 30 sec no messages and after this time I do again receive messages. 

My Test works that way that I send something to the EventHub and wait until it is sucessfully delivered. Afterwards I subscribe to the Eventhub and read all data form the begining. One of this messages should be the message I just send before. But quite often I do not get this message "in time".  I use an EventHub with two partitions and I have two clients running each listining to one partition. 

Any idea what could cause this? I don't know how the receive in particular works but I always receive a block of events....is there an internal wait until the block has a certain size before it got delivered.

Regards

Wolfgang

**Comment by SreeramGarlapati** [comment]
@wofr 
appologies for inconvenience caused. & Thanks a lot for taking time to report the issue.

Can you use version 0.6.10 and set the receiveTimeout (PartitionReceiver.setReceiveTimeout()) to 5 secs.
https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/PartitionReceiver.java#L171

**Comment by wofr** [comment]
Thanks for the fast reply. 
By doing more test today it seems the problem was caused by parellel test-exectution (during the build-process) . I now changed my build process to strictly run tests sequentially (was I thought was anway they default setting....but it wasn't)  and now the problems went away.

Sorry for letting you hunting ghosts.

Regards
Wolfgang

**Comment by SreeramGarlapati** [comment]
@wofr - thanks a lot for reporting back. Am closing this current issue.

Also, I wanted to update you that - we are moving to '0.6.11' - RC is here (I will soon create a notification forum for releases - but for now - will use the issues to track active user :)) :
```
<repositories>
	<repository>  
            <id>azure eventhubs</id>  
            <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1289/</url>  
      </repository>  
</repositories>

<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-eventhubs</artifactId>
      <version>0.6.11</version>
</dependency>
```

it has good improvements both in Sender & Receiver: https://github.com/Azure/azure-event-hubs/pull/149/files 
- Receiver has a minor breaking change - `PartitionReceiver.receive()` now takes an argument - to specify maximum number of messages to be received to control the data pressure building up on the receiver..

**Comment by wofr** [comment]
:) nice.  I will update the version see how it works.
