### ISSUE TITLE
JavaClient: Java client should support TokenProvider model

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#15]
Just like the .Net counter part, we should have some form of TokenProvider model to support
1. token generation from key so that we can use token across the wire protocol instead of key
2. renewal/re-generations of tokens

**Comment by sjkwak** [comment]
We will address this with issue #119.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#15
