### ISSUE TITLE
Missing documentation for publishing over HTTPS from Java

### ISSUE THREAD

**Issue by kittylyst** [Azure/azure-event-hubs#157]
The page at https://github.com/Azure/azure-event-hubs/blob/master/java/PublishingEvents.md makes reference to a "Publishing via HTTPS" section on that page, as a temporary workaround for AMQPS issues or firewall issues. However, no such section appears to exist on the page

**Comment by sujitrect** [comment]
+1. I am hoping for a permanent support of the http/s route through the java event hub client.

**Comment by hmlam** [comment]
Assigning this to John to followup, but we don't currently support https in our API. The right way to support this is through WebSocket but that require Proton-J to provide the require support first.

For now John should fix the documentation to say that Https support is pending.

**Comment by jtaubensee** [comment]
Closing as #253 is merged. We can reopen once Proton-J supports Websockets.
