### ISSUE TITLE
NodeJS: Node client's Connection String should support "HostName" keyword

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#16]
In .Net client the connection string can have the following keyword for specifying connection endpoints:
1. Endpoint=url1[;url2]
2. HostName=host1[;host2]

The difference is that Endpoint requires a URL format, while HostName has no such requirement and internally will create the SB:// URL from hostname.

Event though the original requirement comes from IoT, HostName keyword is designed to be supported by all SB scenario in mind, and so the NodeJS library should also support it.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#8
