### ISSUE TITLE
Non-existent Event Hub name causes NPE in Java client API 

### ISSUE THREAD

**Issue by kittylyst** [Azure/azure-event-hubs#160]
Example code below. 

This behaviour doesn't seem to be documented anywhere, and I would question whether NPE when trying to complete the future and obtain an EventHubClient is really the right response to this type of misconfiguration. Surely a more descriptive exception is possible, even if it's a domain-specific runtime exception that wraps another exception that I can interrogate for a more detailed description of what went wrong.

```java
String namespaceName = "servicename";
String eventHubName = "foobar";
String sasKeyName = "RootManageSharedAccessKey";
String sasKey = "=ItsASecret=";

ConnectionStringBuilder bldr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
String connStr = bldr.toString();

String msgStr = "{\"some\":\"json\"}";
byte[] payloadBytes = msgStr.getBytes();
EventData sendEvent = new EventData(payloadBytes);

CompletableFuture<EventHubClient> clF = EventHubClient.createFromConnectionString(connStr);
EventHubClient ehClient = clF.get();
```

**Comment by SreeramGarlapati** [comment]
@kittylyst - Thanks for reporting the issue. Am looking at it.

**Comment by hmlam** [comment]
https://github.com/Azure/azure-event-hubs/pull/187 should fix this issue.

**Comment by hmlam** [comment]
@kittylyst which version are you using? if you are not using 0.7.2, can you try and see if the problem is still there for 0.7.2?

**Comment by hmlam** [comment]
I changed the repro code to do the following with 0.7.2 and I see the right exception when doing the send.

the exception I see when doing the send is "java.util.concurrent.CompletionException: com.microsoft.azure.servicebus.IllegalEntityException: The messaging entity 'sb://valid_namespace..servicebus.windows.net/bad' could not be found..."

```csharp
    String namespaceName = "valid_namespace";
    String eventHubName = "bad";
    String sasKeyName = "==keyname==";
    String sasKey = "==key==";

    ConnectionStringBuilder bldr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
    String connStr = bldr.toString();

    // I use sync api here, but it doesn't matter @creation whether it is sync or not.		
    EventHubClient client = EventHubClient.createFromConnectionStringSync(connStr);
    byte[] payload = new byte[1024];
    new Random().nextBytes(payload);
    client.send(new EventData(payload)).join(); // <-- exception thrown here
```
