### ISSUE TITLE
NodeJS: express and eventhub SDK

### ISSUE THREAD

**Issue by ThomasAnnerel** [Azure/azure-event-hubs#163]
Dear

We are using an Azure App Service to push messages on a eventhub (+- 2,5 milj messages/hour). The thing we are struggling with a lot is finding a best practice for reusing clients and senders and how to host it in express.

Possibilites:
- new client and sender on every request.
- keep the client alive .
- keep the client and sender alive

I think we are sometimes hitting the connection limit on ServiceBus (+- 5000 connections)

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#5
