### ISSUE TITLE
Node.js Receiver Feedback

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs#166]
Hey Event Hub Users - Is there anyone out there who uses our Node.js library for receiving/processing messages? We are in the midst of reevaluating the design of the EventProcessorHost, and could use some input. If you are interested in helping us out leave a comment below. Thanks!

**Comment by seank-com** [comment]
We are using Node.js, I sent you mail with contact info.

**Comment by jtaubensee** [comment]
Thanks @seank-com - I will add you to the list and reach out to you soon.

**Comment by mauricionr** [comment]
I'm using nodejs EventHub connected with Stream Analytics

**Comment by jtaubensee** [comment]
@mauricionr - So are you only sending data to EventHubs using Node.js, or are you also receiving/processing that data using Node? In most cases, when Stream Analytics is used, customers do not to write any of their own processing logic in EventHubs.

**Comment by mauricionr** [comment]
@jtaubensee I'm sending and receiving data

**Comment by jtaubensee** [comment]
Perfect @mauricionr - I will reach out to you soon. Thanks!

**Comment by mauricionr** [comment]
Ok @jtaubensee.

Thanks!

**Comment by gscott** [comment]
@jtaubensee We are using your node.js library for constructing event receivers.   We have a simple receiver that forwards events off the hub to a metrics charting service.  Happy to provide any feedback we can.

**Comment by gscott** [comment]
#184

**Comment by jtaubensee** [comment]
Hey Guys - Unfortunately our team has been pulled in another direction, so we dont have any immediate plans for a large team sponsored refactoring of the EPH for node. This is still definitely on our radar, and something that we want to do, so I will close this issue for the time being. Stay tuned!
