### ISSUE TITLE
NodeJS: EventHubClient createReceiver causes exception

### ISSUE THREAD

**Issue by kenr** [Azure/azure-event-hubs#167]
Using NodeJS API, EventHubClient.createReceiver result in an error:

outStream.write(buffer);
^

TypeError: Cannot read property 'write' of null
at AttachFrame.Frame.write (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\frames\frame.js:86:12)
at Connection.sendFrame (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\connection.js:336:9)
at ReceiverLink.Link.attach (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:101:27)
at ReceiverLink.Link._attemptReattach (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:204:8)
at Timeout._onTimeout (c:\Users\myusername\dev\msft\web-backend\node_modules\amqp10\lib\link.js:192:10)
at tryOnTimeout (timers.js:224:11)
at Timer.listOnTimeout (timers.js:198:5)

I'm not able to get any of the messages put into the IoT Hub by a device (on the service side). This issue is also reported here: https://github.com/Azure/azure-iot-sdks/issues/621

**Comment by pierreca** [comment]
Looks like the error happens in the amqp10 underneath the event hubs sdk. can you share your code? how you create the client, open the connection etc? also, is your connection string an IoT Hub connection string or an event hubs one?

**Comment by kenr** [comment]
Below is an excerpt of the code. The code fails when connecting (about 4 out of 5 times).
A suspicion is that the initial reply from Azure Iot HUB is too slow, making the AMQP library time out.

```
const EventHubClient = require('azure-event-hubs').Client;

let communicationEventHubClient = EventHubClient.fromConnectionString(
    'HostName=<removed>.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=<removed>' // This is an Iot HUB connection string
);

this.communicationEventHubClient.createReceiver(
    '$Default', '1', { startAfterTime: Date.now() }
).then(receiver => {
    receiver.on('errorReceived', error => { this.emit('error', error); });
    receiver.on('message', this._processMessages.bind(this));

    if (callback) callback();
}).catch(error => {
    if (callback) callback(error);
});

```

**Comment by pierreca** [comment]
Do you have only 1 partition? Looks like you're listening only on partition with id `1`. 

have you tried running the simple sample from the SDK? 
https://github.com/Azure/azure-event-hubs/blob/master/node/samples/simple_eventhubs_client.js

this sample should work with your iothub connection string, and the `eventHubPath` variable set to `undefined`.

Also, can you let me know which version of the amqp10 library was installed in `node_modules`?

**Comment by kenr** [comment]
I've tried with all partitions (4), but the problem is still there.

Versions:
amqp10@2.1.2 (via azure-event-hubs@0.0.2)

I've also tried replacing amqp10 with the latest version (3.1.5) and it yields a better description.
This output  with DEBUG=amqp*

Thu, 16 Jun 2016 10:14:00 GMT amqp10:client session error:  { [AmqpProtocolError: amqp:link:redirect:An AMQP error occurred (condition='amqp:link:redirect').]
  name: 'AmqpProtocolError',
  message: 'amqp:link:redirect:An AMQP error occurred (condition=\'amqp:link:redirect\').',
  condition: 'amqp:link:redirect',
  description: 'An AMQP error occurred (condition=\'amqp:link:redirect\').',
  errorInfo: undefined }
Thu, 16 Jun 2016 10:14:00 GMT amqp10:session detached(messages/events/_ccadfcca-e97b-4479-9489-3c4898d468fa): AmqpProtocolError: amqp:link:redirect:An AMQP error occurred (condition='amqp:link:redirect').
Thu, 16 Jun 2016 10:14:00 GMT amqp10:link messages/events/<removed>_ccadfcca-e97b-4479-9489-3c4898d468fa:0: Transitioning from DETACHED to REATTACHING due to reattach
[Error: error receiving reply from Event Hub management endpoint: An AMQP error occurred (condition='amqp:link:redirect').]

But when I eventually get the AMQP connection up and running (after 10 retries or more today) it takes about five minutes until messages arrive.

**Comment by pierreca** [comment]
I submitted a PR yesterday to fix this and it was merged so version 3.1.6 should not show this error, this being said, there might be other breaking changes in v3.x.x that break. version 2.1.2 should be ok. 

when you say you've tried with all 4 partitions, do you mean all in parallel, using the sample code that I mentioned? or one by one? you should listen to all 4 in parallel. 

can you post the log that you get using `DEBUG=*` and amqp10 2.1.2? Also, what if you set startTime to some time in the past, do you see older messages coming in faster?

**Comment by kenr** [comment]
1) I tried with 3.1.6 and the result is the same as with 3.1.5:

```
Thu, 16 Jun 2016 20:01:24 GMT amqp10:session processing frame:  @detach(22) [handle=0 closed=true error=@error(29) [condition='amqp:link:redirect' description='An AMQP error occurred (condition=\'amqp:link:redirect\').' info={ hostname: 'iothub-ns-devicecomm-43261-db0d256925.servicebus.windows.net',
  'network-host': '<removed by me>.servicebus.windows.net',
  port: 5671,
  address: 'amqps://<removed by me>.servicebus.windows.net:5671/<removed by me>/',
  'com.microsoft:tracking-id': '2d141ede6407466183646c3bd3447d3a-G:10-TimeStamp:06/16/2016 20:01:22' }]]
Thu, 16 Jun 2016 20:01:24 GMT amqp10:framing sending frame:  @detach(22) [handle=0 closed=true error=null] : 0000001102000001005316c00403434140
Thu, 16 Jun 2016 20:01:24 GMT amqp10:link messages/events/_8b7f4336-a819-441c-be41-512df868e7bb:0: Transitioning from ATTACHED to DETACHING due to detachReceived
Thu, 16 Jun 2016 20:01:24 GMT amqp10:link messages/events/_8b7f4336-a819-441c-be41-512df868e7bb:0: Transitioning from DETACHING to DETACHED due to detached
Thu, 16 Jun 2016 20:01:24 GMT amqp10:client session error:  { [AmqpProtocolError: amqp:link:redirect:An AMQP error occurred (condition='amqp:link:redirect').]
  name: 'AmqpProtocolError',
  message: 'amqp:link:redirect:An AMQP error occurred (condition=\'amqp:link:redirect\').',
  condition: 'amqp:link:redirect',
  description: 'An AMQP error occurred (condition=\'amqp:link:redirect\').',

```
I guess com.microsoft:tracking-id is something only MSFT can make sense of. I've marked info that I have removed.

2) I've tried with 4 partitions in parallel (and 1 partition). Using 4 partitions the same message is received 4 times... I have not had time to test the example you mentioned.

3) I'm a bit hesitant to post all the DEBUG=* output since I'm not sure if some if the information contains connection strings or other information related to security. If we can establish a more secure communication channel I can send you the complete output. Here is an excerpt of the output:

```
c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\frames\frame.js:86
  outStream.write(buffer);
           ^

TypeError: Cannot read property 'write' of null
    at AttachFrame.Frame.write (c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\frames\frame.js:86:12)
    at Connection.sendFrame (c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\connection.js:336:9)
    at ReceiverLink.Link.attach (c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\link.js:101:27)
    at ReceiverLink.Link._attemptReattach (c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\link.js:204:8)
    at Timeout._onTimeout (c:\Users\myusername\dev\msft\web-backend\node_modules\azure-event-hubs\node_modules\amqp10\lib\link.js:192:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

Right now my program is not able to get past the AMQP connection issue (tried about 15 times) so I can not provide output regarding setting startAfterTime earlier than Date.now().

**Comment by pierreca** [comment]
what you're saying here:

> 2) I've tried with 4 partitions in parallel (and 1 partition). Using 4 partitions the same message is received 4 times... I have not had time to test the example you mentioned.

should not happen. are you positive it's not old messages?
makes me think there's something wrong with the way you're setting up the receivers. I would strongly encourage you to try the default sample that I pointed at because I tested it, with amqp10@2.1.2 no later than yesterday and it worked fine.

If you cannot get past the amqp-redirect error (which is weird but we can get back to that once you receive your messages properly) you can try to connect directly to the event hubs endpoint that corresponds to your iot-hub. Here's the way to do that with the existing sample:

1. Go to portal.azure.com
2. select your iothub
3. go to settings
4. go to messaging and take note of the values of **Event-hubs compatible endpoint** and **Event-hubs compatible name**

then in the default sample, set the `connectionString` variable to the following:

```
Endpoint=<the endpoint>;SharedAccessKeyName=iothubowner;SharedAccessKey=<your iothubowner policy key>
```

and the `eventHubPath` to the value of the **Event-hubs compatible name**.

Once we know this works properly, then we can tackle either the differences between your code and the sample code when setting up the receivers (if any) and then the amqp-redirect issue.

**Comment by kenr** [comment]
Hi, sorry for the late reply. 

Using the conn-str: Endpoint=sb://<x>;SharedAccessKeyName=<y>;SharedAccesKey=<z> and the IoT name for path I'm able to connect every time. Thanks!

Previously when a connection got established about 1 out of 10 times I used this conn-str format:
HostName=<x>;SharedAccessKeyName=<y>;SharedAccesKey=<z>

Why was I able to connect with the previous connection string at all if it is wrong. Is it possible to add some sort of validation of the conn-str so that users of IoT hub do not have to spend time on this issue?

Regarding the duplication of messages; using the example you pointed me to resolved the issue. Thanks!

**Comment by pierreca** [comment]
The IoT Hub connection string is not "wrong" per se. When using this connection string, the AMQP reply contains a redirection message with all the information for the SDK to connect to the event hubs endpoint. We need to take a look at that, it might be a bug. FYI here's the piece of code that takes care of the redirection:
https://github.com/Azure/azure-event-hubs/blob/master/node/send_receive/lib/client.js#L77

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#4
