### ISSUE TITLE
JavaClient: [azure-eventhubs-eph] the EPH Java (client) API is missing the ability to subscribe to receive only new messages from a Time Instant

### ISSUE THREAD

**Issue by hanoch** [Azure/azure-event-hubs#182]
The azure-eventhubs-eph Java API is missing the option to set an option with a DateTime (Time Instant) parameter, where the partition receivers will only ‘receive’ NEW events from the specified time instant.
This is an existing capability with the ‘azure-eventhubs’ API - EventHubClient.createReceiver(…, final Instant dateTime ) method :
```java
public final CompletableFuture<PartitionReceiver> createReceiver(final String consumerGroupName, final String partitionId, final Instant dateTime)
```
see our usage - https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubClient.java#L708 

see also our attempt with the EPH Java API - https://github.com/Esri/azure-for-geoevent/blob/azure-eventhubs-eph/azure-iot-hub-transport/src/main/java/com/esri/geoevent/transport/azure/AzureEventHubInboundTransport.java#L168.

This functionality is needed for the ArcGIS Azure connectors, to be able to receive only new messages from now on, regardless on whether the event hub is retaining older messages or not.

Setup:

azure-event-hubs version 0.7.2
Multiple (tested with two) Event Hubs with four partitions each.
Muultiple (tested with two) EventProcessorHost instances connecting to specific event hubs with four Partitions each.
Attempting asynchronous reads of NEW messages, no writes

@JamesBirdsall @SreeramGarlapati @velocipedist

**Comment by hanoch** [comment]
@JamesBirdsall 
#183 is now resolved.
Please let us know when you have something to test with for the missing timestamp ('NOW') API pattern.

**Comment by hanoch** [comment]
@JamesBirdsall @SreeramGarlapati 
any progress on this?

**Comment by sjkwak** [comment]
This issue was fixed in previous release.
