### ISSUE TITLE
JavaClient: [azure-eventhubs-eph] the EPH Java (client) API doesn't allow a client application to distinguish between event handlers of different business logic instances and/or different EventProcessorHost instances

### ISSUE THREAD

**Issue by hanoch** [Azure/azure-event-hubs#183]
There is a big design flaw/limitation with the current version of the EPH Java API, which doesn’t allow us to simply register our own instance of an IEventProcessor handler (which we need as a callback method when an event is received), and instead, the EventProcessorHost is instantiating new instances of our IEventProcessor custom class. This is raising a big limitation and complicates the application implementation to the point where it is almost no longer possible to figure out which feed the onEvents method (as well as onError, onOpen, onClose, etc.) is being invoked for, and makes it impossible to encapsulate the onEvents() logic within the same application class instance that is in charge of this specific feed (events received from an event hub) logic.

In other words, it will be MUCH BETTER to be able to do something like:
```java
host = new EventProcessorHost(eventHubPath, consumerGroupName, eventHubConnectionString, storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setExceptionNotification(new ErrorNotificationHandler()); 
IEventProceesor myEventProcessorInstance = new MyEventProceesor(…);  // API enhancement suggestion option 1
host.registerEventProcessor(myEventProcessorInstance, options).get();
```

Or even:
```java
host = new EventProcessorHost(eventHubPath, consumerGroupName, eventHubConnectionString, storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setExceptionNotification(new ErrorNotificationHandler());
options.setEventProcessorNotifications(new MyEventProceesor(…));  // API enhancement suggestion option 2
host.registerEventProcessor(options).get();
```

Rather than:
```java
host = new EventProcessorHost(eventHubPath, consumerGroupName, eventHubConnectionString, storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setExceptionNotification(new ErrorNotificationHandler());
host.registerEventProcessor(EventProcessor.class, options).get();  // using EventProcessor.class is problematic
```

The suggested API allows the API user to instantiate the MyEventProcessor instance, rather than letting the EventProcessorHost 'framework' do it for the user.  This allows the user to control those instances, and implement the correct logic onEvents (and other event handler callbacks), depending on the feed.

I understand that this means that the EventProcessorHost instance will need to share the one IEventProcessor instance between all its event-clients and/or partition-receivers, but this is okay, since the handler methods have the context object as a parameter.

See our attempt with the EPH Java API:
https://github.com/Esri/azure-for-geoevent/blob/azure-eventhubs-eph/azure-iot-hub-transport/src/main/java/com/esri/geoevent/transport/azure/AzureEventHubInboundTransport.java#L174.
https://github.com/Esri/azure-for-geoevent/blob/azure-eventhubs-eph/azure-iot-hub-transport/src/main/java/com/esri/geoevent/transport/azure/AzureEventHubInboundTransport.java#L239
https://github.com/Esri/azure-for-geoevent/blob/azure-eventhubs-eph/azure-iot-hub-transport/src/main/java/com/esri/geoevent/transport/azure/AzureEventHubInboundTransport.java#L279

Notice that the for the EventProcessorHost 'framework' to be able to instantiate an instance of the  custom EventProcessor class (implements IEventProcessor), the (inner) EventProcessor class will need to be marked as static, and therefore will not be able to invoke any non-static methods, such as the (outer class) receive() method, which has specific instance (feed) related logic to follow.

Setup:

azure-event-hubs version 0.7.2
Multiple (tested with two) Event Hubs with four partitions each.
Muultiple (tested with two) EventProcessorHost instances connecting to specific event hubs with four Partitions each.
Attempting asynchronous reads of NEW messages, no writes

@JamesBirdsall @SreeramGarlapati @velocipedist

**Comment by SreeramGarlapati** [comment]
Thanks for reporting the issue @hanoch!

I believe – the main concern that you are trying to address by proposing the below solution is: “**_registering your own instance of IEventProcessor_**”.

Use EventProcessorHost.registerEventProcessorFactory to achieve the same. Here’s how code will looklike:

```
host = new EventProcessorHost(eventHubPath, consumerGroupName, eventHubConnectionString, storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setExceptionNotification(new ErrorNotificationHandler());
host.registerEventProcessorFactory(new IEventProcessorFactory<MyEventProcessor>() { 
						Override public T createEventProcessor(PartitionContext context) throws Exception { return new MyEventProceesor(…);
						}},
					options).get();


```

**Comment by hanoch** [comment]
no, that is not going to help since the only way to resolve this issue is to let me pass in the actual instance of the IEventProcessor I created in my class context, and not allow the framework to create a new instance by itself.
@SreeramGarlapati - please reopen this issue.

**Comment by hanoch** [comment]
@JamesBirdsall 
I was able to use the IEventProcessorFactory pattern to receive messages correctly my my IEventProcessor instance:
https://github.com/Esri/azure-for-geoevent/commit/536fe0b128a2c32cc2b08faeaba7b260445b337a

The only remaining issue that prevents us from using the EPH Java API is the missing timestamp ('NOW') API pattern, as described in #182.
