### ISSUE TITLE
node.js event receiver: sometimes the messages just stop coming until we restart

### ISSUE THREAD

**Issue by gscott** [Azure/azure-event-hubs#184]
We're taking events straight off a hub where we have a read-only SAS.   The events are forwarded to a metrics charting service over a TCP connection (not shown below, except for the `socket.write()` you see in the for loop.

Using a variation of the event hubs sample code in this repo we wrote a client below.  I left out the initialization code.  This app starts, we successfully open the `ehClient`, we start seeing thousands of messages flowing through -- and then after some time, could be twenty minutes, could be a few hours, we stop getting any `message` events, until we restart.  I even put the `process.exit()` in there to force myself to quit when an error comes in, but we never get an error.

``` javascript
ehClient.open()
  .then(ehClient.getPartitionIds.bind(ehClient))
  .then(function (partitionIds) {
    return partitionIds.map(function (partitionId) {
    return ehClient.createReceiver(EH_CONSUMER_GROUP, partitionId,  { 'startAfterTime' : receiveAfterTime}).then(function(receiver) {
      receiver.on('errorReceived', (err) => {
        console.log( 'Event hub error: ' + err )
        process.exit( 1 ) 
      })
      receiver.on('message', function (message) {
        for ( let stat of message.body ) {
          socket.write( stat.data.app ) // we don't get errors on this socket
         } 
     })
   })
 })

```

Anything obviously wrong?  I'm a little unsure on where to debug this.

**Comment by gscott** [comment]
I could just be getting socket timeouts which has zero to do with hubs but when those happen I catch that error in a socket.on().   

I will run the app for a while without any TCP writing, just processing and throwing away messages and see what happens.

**Comment by gscott** [comment]
After removing all TCP stuff in the for loop we stopped receiving messages after 16,184 received.  Still looking for ideas.

**Comment by gscott** [comment]
Any ideas?  I see you're planning to refactor the receiver code -- should I be heading that way?

**Comment by gscott** [comment]
/cc @jtaubensee 

We have not been able to figure this one out.

**Comment by jtaubensee** [comment]
@gscott - Unfortunately our team has been pulled in another direction, so we font have any immediate plans for a large team sponsored refactoring of the EPH for node. This is still definitely on our radar, and something that we want to do. Stay tuned!

**Comment by rjeike** [comment]
@gscott did you close this because it is resolved for you?  We are still seeing this issue.  Can you reopen?  I'd like to see if we can get some MS attention on it.

**Comment by gscott** [comment]
@rjeike No, not resolved.  In fact, the unreliable Node support caused us to drop using event hubs from the solution we were considering at the time.  We didn't want to do Java or .NET, the only supported SDKs, and once @jtaubensee indicated above the team had pivoted elsewhere, that was the signal to move on.   But I'd *love* to have a great Node.js solution for using event hubs.

**Comment by glegrain** [comment]
We have the same issue. **Has anybody figured out a workaround?** Our Web App needs to be restarted every few hours or so to continue receiving event from the IoT Hub.

**Comment by rjeike** [comment]
@glegrain our "workaround" was to ditch this Node solution and implement it in .Net.

**Comment by beneuto** [comment]
I'm using this within node-red but here is my workaround:

1. Initiate the receiver on a regular basis (interval injection in node-red)
2. Increment version variable
3. In the receiver.on function check whether the receiver is the latest version and if not force a close (  client.close()   )
4. Need to keep a record of the last known iothub-enqueuedtime and use this for the startAfterTime option for the receiver to avoid losing messages between a receiver crash and the next run
5. I've found another bug in that the receiver will return messages slightly before the startAfterTime so I put in another check to filter out such messages later in the process flow

Not the most elegant solution but it works for me.

**Comment by sabeegrewal** [comment]
Hey everyone, we'll be fully supporting Node.js within the month. The code will be hosted here: https://github.com/azure/azure-event-hubs-node. Open an issue there for support! 👍
