### ISSUE TITLE
[0.7.2] Access Iot-Hub via EventHub-Compatible interface fails

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#185]
Hi!

I tried to use the lib to read data from an Iot-Hub by using the Event-hub compatible endpoint (described here (https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide/)

Unfortunatly it fails as it seems the lib could not build the right URI
The portal does give me the following URI

"sb://ihsuprodamres027dednamespace.servicebus.windows.net/"

Following the instrouction in the articel above I used the following setup 
`iot.eventhub.namespace = "ihsuprodamres027dednamespace"`
`iot.eventhub.name = "ihsuprodamres027dednamespace.servicebus.windows.net"`
`iot.eventhub.sasKeyName = "iothubownder"`
`iot.eventhub.sasKey = "********************"`
`iot.eventhub.consumerGroup = "tester"`
`iot.eventhub.nrOfPartions = 2`

Ending up in this exception
`10:30:26.099 ERROR Failed to create partition receiver for partition 0: com.microsoft.azure.servicebus.IllegalEn<tityException: The messaging entity 'sb://ihsuprodamres027dednamespace.servicebus.windows.net/ihsuprodamres027dednamespace.servicebus.windows.net/consumergroups/tester/partitions/0' could not be found. TrackingId:c95004aef3d4469b93fcfafa67badecc_G11, SystemTracker:gateway2, Timestamp:7/8/2016 8:30:21 AM, errorContext[NS: ihsuprodamres027dednamespace.servicebus.windows.net, PATH: ihsuprodamres027dednamespace.servicebus.windows.net/ConsumerGroups/tester/Partitions/0, REFERENCE_ID: 55ceca_c95004aef3d4469b93fcfafa67badecc_G11, R_TYPE: NON_EPOCH]`

After switching to this setup (as the generated URI in the frist approach is obviously  to long)

`iot.eventhub.namespace = "ihsuprodamres027dednamespace"`
`iot.eventhub.name = ""`
`iot.eventhub.sasKeyName = "iothubownder"`
`iot.eventhub.sasKey = "*******"`
`iot.eventhub.consumerGroup = "tester"`
`iot.eventhub.nrOfPartions = 2`

I got following exception 
`Failed to create partition receiver for partition 1: com.microsoft.azure.servicebus.IllegalEntityException: The messaging entity 'sb://ihsuprodamres027dednamespace.servicebus.windows.net/null/consumergroups/tester/partitions/1' could not be found. TrackingId:ef68d38a09434541bfc840364aa4d1a5_G14, SystemTracker:gateway2, Timestamp:7/8/2016 8:32:07 AM, errorContext[NS: ihsuprodamres027dednamespace.servicebus.windows.net, PATH: null/ConsumerGroups/tester/Partitions/1, REFERENCE_ID: d65d21_ef68d38a09434541bfc840364aa4d1a5_G14, R_TYPE: NON_EPOCH]`

Finnaly it seems to be a problem how the lib builds the URI. The expected URI should be
`sb://ihsuprodamres027dednamespace.servicebus.windows.net/`
By using the lib I only could generate this URI
`sb://ihsuprodamres027dednamespace.servicebus.windows.net`/ihsuprodamres027dednamespace.servicebus.windows.net/consumergroups/tester/partitions/0 (approach one)

or this one (approach two)
`sb://ihsuprodamres027dednamespace.servicebus.windows.net/**null**/consumergroups/tester/partitions/1`

The second one seems quite promising but here the problem is that an empty "event-hub" name ends up in a Null.

Could this be fixed?

**Comment by sjkwak** [comment]
For iot.eventhub.name, you can get it from the setting.
 iot.eventhub.name = "Event Hubs-compatible name"  <-- copy actual value from the portal

**Comment by hmlam** [comment]
Btw, which version of the library are you using?




On Fri, Jul 8, 2016 at 9:48 AM -0700, "SJ" <notifications@github.com<mailto:notifications@github.com>> wrote:


For iot.eventhub.name, you can get it from the setting.
iot.eventhub.name = "Event Hubs-compatible name" <-- copy actual value from the portal

-

**Comment by wofr** [comment]
I'm using [0.7.2] like I wrote in the header :)
It worked with the following seeting 

`iot.eventhub.namespace =  <--Event Hub-compatible endpoint (first part of the uri)`
`iot.eventhub.name = <-- Event Hub-compatible name`

E.g 
Event Hub-compatible name: "iothub-ehub-my-iot-tes-51280-b38da5b2f6"
Event Hub-compatible endpoint : "sb://ihsuprodamres426dednamespace.servicebus.windows.net/"

`iot.eventhub.namespace = "ihsuprodamres426dednamespace"`
`iot.eventhub.name = "iothub-ehub-my-iot-tes-51280-b38da5b2f6"`
