### ISSUE TITLE
PartitionReceiver is ignoring non-transient errors

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#190]
This was found during investigation of https://github.com/Azure/azure-event-hubs/issues/180

Using the following code, while looping if we delete the entity, the receive loop will happily keep on running.

``` csharp
	EventHubClient client1 = EventHubClient.createFromConnectionStringSync(connection);
	EventHubClient client2 = EventHubClient.createFromConnectionStringSync(connection);
	PartitionReceiver receiver1 = client1.createReceiverSync("$Default", "0", PartitionReceiver.START_OF_STREAM);
	receiver1.setReceiveTimeout(Duration.ofSeconds(3));
	PartitionReceiver receiver2 = client2.createReceiverSync("$Default", "1", PartitionReceiver.START_OF_STREAM);
	receiver2.setReceiveTimeout(Duration.ofSeconds(3));
	int loop = 1;
	while (true)
	{
		try
		{
			// while this is running delete the entity, this loop will 
			// continue to run without throwing any error
			System.out.printf("Loop %s... ", loop++);
			receiver1.receiveSync(1);
			receiver2.receiveSync(1);
			System.out.println("Done");
		}
		catch(Exception e)
		{
			System.out.printf("throws [%s]:%s\n", e.getClass().getName(), e.getMessage());
		}
	}
```

**Comment by hmlam** [comment]
Adding Sreeram, as after investigation looks like it is similar to the threading fix that we did for send path. Basically from traces we see that reconnect hit "not-found" error but that error did not stop the pending receive loop. Live debug in Eclipse actually did not capture the reconnect error, which makes me suspect that the reconnect is not happening in the right thread.

**Comment by SreeramGarlapati** [comment]
PR #211 addresses this issue
