### ISSUE TITLE
  [Version 0.7.4,; Java-client] OnReceive get called with parameter events == Null

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#191]
When subscribe to an EventHub the OnReceive method gets called periodically with an empty parameter “events” (events == Null). For me this behavior is somehow unexpected. OnReceive should only be called if data are available and not with  null values. (already discussed here https://github.com/Azure/azure-event-hubs/issues/168#issuecomment-232700121)

`partitionReceiver.setReceiveHandler(new PartitionReceiveHandler(100) {`
`override def onError(throwable: Throwable): Unit = {`
`log.error("PartitionReceiver failed with error {}", throwable)`
`self ! EventHubPartitionReceiverFailed(partitionId,throwable.getMessage)`
`}`

`override def onReceive(events: java.lang.Iterable[EventData]): Unit = {`
`log.info("Recieved events {}",events) // log output “INFO Recieved events null ”`
`readFromStreamAnalyticsPreProcessedStream( events.asScala)`
`}`

**Comment by SreeramGarlapati** [comment]
@wofr : can you add a null-check before processing the events ? 

As explained - we had a requirement - to support a Knob in EventProcessorHost (https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs-eph/src/main/java/com/microsoft/azure/eventprocessorhost/EventProcessorOptions.java#L170) and hence had to enable this.

However, you did mention that although you have data on the Receiving partition - intermittently, there are few calls which are returning ```null```. We are looking into this problem.

**Comment by hmlam** [comment]
@SreeramGarlapati can you check to see if this is related to https://github.com/Azure/azure-event-hubs/issues/190 ?

**Comment by hanoch** [comment]
I also reported this with #181 -
https://github.com/Azure/azure-event-hubs/issues/181#issuecomment-231855578

**Comment by SreeramGarlapati** [comment]
@hmlam : this might not be related to #190

**Comment by wofr** [comment]
Of course I added a check to avoid a nullpoint exception :) nevertheless its a little bit nasty. What I not observerd is that the receive stopped working at all.

**Comment by SreeramGarlapati** [comment]
@wofr & @Hanoch 
We fixed the issue in 0.7.7 - where onReceive gets invoked with events==null eventhough there are events on the hub. Please validate...

We did not fix the onReceive getting called with evens==null - when there are no events on the EventHub - Yet. it is in my radar...

**Comment by SreeramGarlapati** [comment]
This is in master - will be released as part of `0.8.1`. Thx for reporting the issue @wofr & @hanoch.
