### ISSUE TITLE
EPH crashes due to high memory usage by large number of threads

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs#192]
EPH client process memory usage hit almost 3GB and then process crashed due to not able to allocate more resources. Attached screenshot shows the memory footprint during the run.

<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.

![capture](https://cloud.githubusercontent.com/assets/16924470/16926315/fbccd7f8-4cdc-11e6-978f-fd204468eced.PNG)

**Comment by sjkwak** [comment]
#283

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#19
