### ISSUE TITLE
[Version 0.7.4; Java-client] Delivery of message fails silently 

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#194]
My application does constantly send data to an event-hub, which worked properly for hours, but after 12 hours it seems to stop working silently. I did not found any exception in my logs nor did I found something on std.out or std.errorr. 

The application was sending data for hours but after a certain point of time none of them showed up in the Eventhub. Also I do not get any response from the send-methode. Usually I do see an “successful” or sometimes a “failed” log entry, but in this case I simple get nothing. I kept the application running the whole weekend but none but the behavior did not change. A work around for me would be to wrap the Future with a second one which gives me a timeout but in the older version I always received a time-out from the event-hub client. Has this changed?

Below a code snippet 

`FutureConverters.toScala(eventHubClient.send(sendEvent)).onComplete {`
`  case Success(void) =>`
`    log.info("Successfully send meta-data {} to the MetaData-EventHub {}.{}",curMsg ,eventHubName, namespaceName)`
 ` case Failure(msg) =>`
 `   log.error("Failed to send message to MetaData-EventHub due to {}", curMsg)`
`}`

**Comment by wofr** [comment]
For the purpose of testing I tried the following. I started my application and waited until it starts to send (send async) data. After a while I switched of the network connection.  
On the system.out I saw exception dropping but none of them made it into my application. The send method just stopped silently working like described above.  I such a case I would expect to the send function to fail (Future complete with failure)

Output on system.out 

`REporter started`

`Jul 19, 2016 8:49:41 AM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[data-ingest-services.servicebus.windows.net:5671], error[connection aborted]`
`Jul 19, 2016 8:49:41 AM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[data-ingest-services.servicebus.windows.net:5671], error[connection aborted]`
`Jul 19, 2016 8:49:41 AM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[data-ingest-services.servicebus.windows.net:5671], error[connection aborted]`
`Jul 19, 2016 8:49:41 AM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[data-ingest-services.servicebus.windows.net:5671], error[connection aborted]`
`Jul 19, 2016 8:49:42 AM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.IllegalArgumentException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:354)
java.lang.Thread.run(Unknown Source)Cause: null
java.nio.Buffer.position(Unknown Source)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:354)
java.lang.Thread.run(Unknown Source)
Jul 19, 2016 8:49:42 AM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.IllegalArgumentException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:354)
java.lang.Thread.run(Unknown Source)Cause: null
java.nio.Buffer.position(Unknown Source)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:354)
`

**Comment by SreeramGarlapati** [comment]
@wofr - we fixed this in 0.7.7. Please give it a try...

**Comment by wofr** [comment]
I do so :)

**Comment by wofr** [comment]
I would love to. Do you have an repo for me?  I just found this https://oss.sonatype.org/content/repositories/commicrosoftazure-1345/ which included 0.7.6

**Comment by wofr** [comment]
Looks good so far. 
Last time the problems ocurred after 12 hours, lets see if my test keeps running

**Comment by SreeramGarlapati** [comment]
Thanks for quick response @wofr...

**Comment by wofr** [comment]
Looks good to me! No silent fails observed in the last 24 hours

**Comment by SreeramGarlapati** [comment]
Great.. Thanks @wofr!
