### ISSUE TITLE
EPH stopped receiving from all partitions after hitting IllegalArgumentException couple of times.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs#200]
- Single process
- Single host
- 4 partitions EH

Host ran quite fine for 3 hours in our stress tests and then hit multiple IllegalArgumentExceptions then completely stopped delivering messages.

<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: Jul 25, 2016 8:32:04 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: WARNING: UnHandled exception while processing events in reactor:
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: java.lang.IllegalArgumentException
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: java.lang.Thread.run(Unknown Source)Cause: null
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: java.nio.Buffer.position(Unknown Source)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<8084.20> 07/25/2016 20:32:04 - Error: JAVA-Receiver_0<stderr>: java.lang.Thread.run(Unknown Source)

**Comment by sjkwak** [comment]
This issue is related to https://issues.apache.org/jira/browse/PROTON-1275. We are going to release new Java client SDK with new proton-J version 0.15.0.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#18
