### ISSUE TITLE
Java client is not working on JDK 7

### ISSUE THREAD

**Issue by sasincj** [Azure/azure-event-hubs#201]
I'm using Azure HDInsight Storm with eventhubs. For publishing some output data to eventhub I've included this library. But it throws an error. HDInsight comes with OpenJDK7. Is there a way to solve this issue.

**Comment by jtaubensee** [comment]
@sasincj - What's the error that you are seeing?

**Comment by gridcellcoder** [comment]
Here's an example when compiling using maven and JDK1.7:
 
```
[ERROR] /tmp/azure-event-hubs/java/azure-eventhubs/src/main/java/com/microsoft/azure/servicebus/MessageReceiver.java:[678,98] cannot find symbol
[ERROR] symbol:   class Duration
```

You are using 1.8 classes such as `Duration`  which is @since 1.8 but your pom is marked as 1.7. We need a pure 1.7 library because the current HDInsight clusters use 1.7. 

The version 0.7 tag for example has this in the pom:
```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-compiler-plugin</artifactId>
   <version>3.5</version>
   <configuration>
      <source>1.7</source>
      <target>1.7</target>
      <optimize>true</optimize>
      <showDeprecation>true</showDeprecation>
      <showWarnings>true</showWarnings>
   </configuration>
</plugin>
```

but uses 1.8 classes and libraries

**Comment by jtaubensee** [comment]
@gridcellcoder / @sasincj - Our library has a couple of dependencies on Java8, because we use things like CompletableFuture, and lambdas. We do not have any plans to make our library compatible with Java7, but the HDInsight team will eventually have a Java8 compatible library.

**Comment by jtaubensee** [comment]
Closing since there are no plans for the Java client to work on version 7.
