### ISSUE TITLE
Exception java.lang.NoSuchMethodError: org.apache.qpid.proton.reactor.Reactor.connectionToHost

### ISSUE THREAD

**Issue by mayuraviraj** [Azure/azure-event-hubs#243]
I'm using azure-event-hubs 0.8.0 for my project. I have implemented the azure event hub message receiver via IEventProcessor. But when the message consumer start it throws following exception.

```
[2016-08-30 16:11:22.471] boot - 29135  INFO [pool-28-thread-1] --- TestEventProcessor: Partition 0 is opening.
Exception in thread "Thread-16" Exception in thread "Thread-15" java.lang.NoSuchMethodError: org.apache.qpid.proton.reactor.Reactor.connectionToHost(Ljava/lang/String;ILorg/apache/qpid/proton/engine/Handler;)Lorg/apache/qpid/proton/engine/Connection;
	at com.microsoft.azure.servicebus.MessagingFactory$1.onReactorInit(MessagingFactory.java:86)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:209)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.engine.impl.EventImpl.delegate(EventImpl.java:129)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:114)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:272)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NoSuchMethodError: org.apache.qpid.proton.reactor.Reactor.connectionToHost(Ljava/lang/String;ILorg/apache/qpid/proton/engine/Handler;)Lorg/apache/qpid/proton/engine/Connection;
	at com.microsoft.azure.servicebus.MessagingFactory$1.onReactorInit(MessagingFactory.java:86)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:209)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.engine.impl.EventImpl.delegate(EventImpl.java:129)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:114)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:272)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
	at java.lang.Thread.run(Thread.java:745)
[2016-08-30 16:13:29.323] boot - 29135  INFO [pool-28-thread-4] --- TestEventProcessor: Partition 0 is closing for reason LeaseLost
```

Following are my code

**Event Processor**

```
public class TestEventProcessor implements IEventProcessor {

    @Override
    public void onOpen(PartitionContext context) throws Exception {
        System.out.println("Partition is opening. : " + context.getPartitionId());
    }

    @Override
    public void onClose(PartitionContext context, CloseReason reason) throws Exception {
        System.out.println("Partition is closing for reason : " + context.getPartitionId() + " : " + reason.toString());
    }

    @Override
    public void onError(PartitionContext context, Throwable error) {
        System.out.println("Partition onError: " + context.getPartitionId()  + " : " + error.toString());
    }

    @Override
    public void onEvents(PartitionContext context, Iterable<EventData> messages) throws Exception {
        System.out.println("Partition got message batch : " + context.getPartitionId());
    }
}
```

Registering the Event consumer
````
EventProcessorHost host = new EventProcessorHost(hubName,
                consumerGroupName,
                iotHubMessageConnectionString,
		storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
        options.setExceptionNotification((errorArg) -> System.out.println("Host received error " + errorArg.getHostname() + " : " + errorArg.getAction() + " : " +  errorArg.getException()));
        try {
            host.registerEventProcessorFactory(new TestEventProcessor(), options).get();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
````

**Comment by SreeramGarlapati** [comment]
Do you have a pom entry for `apache/proton-j libraries` which is **older than** `0.13.0` ? or does any other libraries that your project depends on have ? 

`org.apache.qpid.proton.reactor.Reactor.connectionToHost` was a new API added in `0.13.0`.

**Comment by wangxhere** [comment]
I also encountered the same issue. Also I didn't have proton-j in my pom.xml, after adding the dependency manually for 0.14.0, the issue persists.

**Comment by wangxhere** [comment]
@SreeramGarlapati 
I found that iothub-java-client which is in my pom.xml has an underlying dependency on 0.12.0 proton-j. Please verify whether the following temporary workaround is complete, thanks.

		
		<dependency>
			<groupId>com.microsoft.azure.iothub-java-client</groupId>
			<artifactId>iothub-java-service-client</artifactId>
			<version>1.0.9</version>
			<exclusions>
				<exclusion>
					<groupId>com.microsoft.azure.iot</groupId>
					<artifactId>proton-j-azure-iot</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by SreeramGarlapati** [comment]
@wangxhere 
That should work. But, the iot-sender might fail. If you have separate running instances of senders & receivers and are trying to write a common library - this approach should work - otherwise - you need to separate them into different executables.

**Comment by wangxhere** [comment]
@SreeramGarlapati 
Yes I am putting both sender and receiver into the same package. Meanwhile it seems that my receiving side is still not working, just unable to receive any message my device sends. Although sending side is working normally. I'm still figuring out what else went wrong.
Is it the whole part of proton-j-azure-iot is about proton-j and nothing else?

**Comment by SreeramGarlapati** [comment]
We don't have any `known issues` on receivers (use the latest event-hubs sdk `0.8.2`).
Did you create receivers to all partitions? Event from a device would land on a specific partition to which the deviceId is hash'ed to.

@dcristoloveanu/@jasmineymlo from iot-sdk team can help with any IOT related questions.

**Comment by wangxhere** [comment]
@SreeramGarlapati @dcristoloveanu 
I'm using EPH to receive from the eventhub compatible endpoint. Got trouble when trying to use 0.7.2 eph to get around from the former proton-j issue, but was unable to connect (HTTP 401). After using 0.8.2 eph, I can connect but still am unable to receive Eventhub messages (i.e. the onEvent is never called). However when I try to use .net version to receive from IoT hub c2d endpoint directly, it prompts me that another receiver is on the same consumer group. That totally confused me. I'm not sure whether my EPH setting is correct or not, just following the tutorial on MSDN but no message is received at all. Meanwhile when I stopped my EPH and open the IoT Hub Device Explorer to receive message, hoping to receive those queued messages, there's NO message at all.

**Comment by wangxhere** [comment]
@SreeramGarlapati @dcristoloveanu 
My other issue resolved. The line:
this.partitionReceiver.setReceiveHandler(...)
of /java/azure-eventhubs-eph/src/main/java/com/microsoft/azure/eventprocessorhost/EventHubPartitionPump.java
was not executed successfully without an exception raised, due to some confliction caused by putting both eventhub-client and eph library in pom.xml. I've removed eventhub-client.

**Comment by SreeramGarlapati** [comment]
So @wangxhere - can you please summarize the state of this issue now - where exactly can we help?

**Comment by wangxhere** [comment]
@SreeramGarlapati 
For me the issue is resolved now. Don't know whether the original author has anything requiring following up.

**Comment by mayuraviraj** [comment]
My issue is also resolved. We were trying to share the same message hub in different developers. We solved it using consumer groups ( one consumer group for one developer ). Also we had the same issue using iothub-java-service-client with EPH library in same module. We have separated them as a solution to proton-j dependency problem.

**Comment by SreeramGarlapati** [comment]
@mayuraviraj @wangxhere : Great to hear - u folks are making progress.!
