### ISSUE TITLE
JavaClient: define explicit contracts that needs to run on Reactor Thread & in a specific order

### ISSUE THREAD

**Issue by SreeramGarlapati** [Azure/azure-event-hubs#244]
Best examples for this are:
- CreateConnection should be called only from ScheduleOnReactorThread()
- sender/receiver workItems should be enqueued before invoking any proton code (reactor) - which will ensure the onError event to enact on the enqueued work.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#9
