### ISSUE TITLE
EPH: pump stops working after idle time

### ISSUE THREAD

**Issue by PeterKelecom** [Azure/azure-event-hubs#254]
single process
single host
2 partition EH 

If no new events are being sent for ~45 minutes and a device starts sending new messages after that idle time, the event processor does not pick up those messages. Upon restart, the events are picked up and processed immediately. 
It looks like the pump is not releasing the lease but stops pumping the messages.

**Comment by PeterKelecom** [comment]
After some investigation I found out the issue lies with either the MessageReceiver class. I can see the messages being picked up there, but for some reason they never reach the PartitionReceiver.

**Comment by SreeramGarlapati** [comment]
@PeterKelecom - Thanks for reporting the issue. We found the bug - working on the fix... Its in the PartitionReceiver - PUMP.

Thanks to @serkantkaraca who located the bug..

**Comment by PeterKelecom** [comment]
Thanks, that's great. 

Do you mind telling me where/what the issue was? I've been looking at the code for 2 days but didn't find the bug so I'm intrigued.

**Comment by SreeramGarlapati** [comment]
The bug is around here: https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/PartitionReceiver.java#L419

Pump exits here in case of Transient errors and doesn't notify (onError).

**Comment by PeterKelecom** [comment]
Thanks, I appreciate that.

**Comment by SreeramGarlapati** [comment]
we just released `eventhubs client version 0.8.2` which has the fix for this issue (which should be available in Maven central repo in another 2hrs).
@PeterKelecom - please try & let us know how it went...

**Comment by PeterKelecom** [comment]
Issue seems to be resolved when working with the git pull. 

However, when I use maven (azure-eventhubs 0.8.2, azure-eventhubs-eph 0.8.1) my partitions are opened but nothing is being read from them. No exceptions/anyhing else in the eventprocessorhost trace logs either.

**Comment by SreeramGarlapati** [comment]
`EPH 0.8.1` explicitly imports `azure-eventhubs 0.8.1`.
Use <a href="https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html">maven dependencyManagement</a> to explicitly import the `azure-eventhubs 0.8.2`.

**Comment by PeterKelecom** [comment]
I'm not replicating the bug, it's not processing any messages at all (not on start up, not when sending new ones during processor run) when I use 0.8.2. Opening partitions but then nothing. Maven dependency tree looks like this: 

[INFO] +- com.microsoft.azure:azure-eventhubs-eph:jar:0.8.1:compile
[INFO] |  +- com.microsoft.azure:azure-eventhubs:jar:0.8.2:compile
[INFO] |  |  +- org.apache.qpid:proton-j:jar:0.14.0:compile
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.49:compile
[INFO] |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.49:compile

**Comment by SreeramGarlapati** [comment]
So, it works with the `git pull` & doesn't with `0.8.2`. I am fairly certain this has to do with mvn dependencies. Make sure you have this...
```
<dependencyManagement>
  <dependencies>
		<dependency>
		      <groupId>com.microsoft.azure</groupId>
		      <artifactId>azure-eventhubs</artifactId>
		      <version>0.8.2</version>
	  	</dependency>
	  	<dependency>
	      <groupId>com.microsoft.azure</groupId>
	      <artifactId>azure-eventhubs-eph</artifactId>
	    	<version>0.8.1</version>
	    	<exclusions>
		    	<exclusion>
		    	<groupId>com.microsoft.azure</groupId>
			    <artifactId>azure-eventhubs</artifactId>
			</exclusion>
		  </exclusions>
		</dependency>
  </dependencies>
</dependencyManagement>
<dependencies>
	<dependency>
	      <groupId>com.microsoft.azure</groupId>
	      <artifactId>azure-eventhubs</artifactId>
	 </dependency>
	 <dependency>
	      <groupId>com.microsoft.azure</groupId>
	      <artifactId>azure-eventhubs-eph</artifactId>
	 </dependency>
</dependencies>
```

I am giving it a try...

**Comment by SreeramGarlapati** [comment]
Sorry - my bad. We needed `EPH-0.8.2` as well for EPH to work - as we changed the return parameter of `setReceiveHandler()` API.

I just released `EPH-0.8.2` - let me know how it goes.

**Comment by PeterKelecom** [comment]
I'm guessing something went wrong with the release. The jar is only 2kb and it can't be opened as an archive. 
eclipse is also telling me there is an issue with the archive: 
![image](https://cloud.githubusercontent.com/assets/22001549/18541812/d0e1aa68-7b27-11e6-86ab-cad01d10446a.png)

**Comment by SreeramGarlapati** [comment]
my bad again..
Tried re-publishing it. Will wait for a couple hours to verify if it went well or not. If not, will publish a 0.8.3.

**Comment by PeterKelecom** [comment]
Looking good now. Will do a few more tests over the next couple of days and let you know.

**Comment by SreeramGarlapati** [comment]
Great Thanks @PeterKelecom.

If you see that this specific issue is fixed - close it. If you find newer issues related to this - you can always create new one and link this. It will simplify tracking current issues than (vs) looking at a long running issue to find out what the thread is actually about :)

**Comment by PeterKelecom** [comment]
@SreeramGarlapati works fine now. Thanks!
