### ISSUE TITLE
initial offset provider ignored

### ISSUE THREAD

**Issue by PeterKelecom** [Azure/azure-event-hubs#256]
I've set my function to return the current datetime so that the processor will only start processing the new incoming messages. However, the processor still starts from the start of the stream. 
Code below: 

EventProcessorHost host = new EventProcessorHost(eventHubName, consumerGroupName, eventHubConnectionString.toString(), storageConnectionString);
EventProcessorOptions options = new EventProcessorOptions();
options.setInitialOffsetProvider((partitionId) -> { return Instant.now();});
try {
     host.registerEventProcessorFactory(factory, options).get();
}

**Comment by JamesBirdsall** [comment]
What version are you using? The ability to start at a timestamp was introduced in release 0.7.8.

Note that the initial offset provider is ignored in favor of a checkpoint for a partition. If you at some time checkpointed the partitions at the start of the stream, that would explain what you're seeing.

**Comment by PeterKelecom** [comment]
Using version 0.8.1.

Fresh consumergroup so there shouldn't be any checkpoints..

**Comment by JamesBirdsall** [comment]
This is a head-scratcher: your scenario, including an identical lambda, is the first test I wrote after adding this feature, and it still passes for me.
I double-checked the code and there isn't much to go wrong: the Instant that your lambda returns is passed down through the layers unmodified, until it is converted to a number of milliseconds, which is inserted in a filter expression that is passed to the service. If that part were broken I'd expect an exception back from the service.
Is there anything unusual about the clock or the time zone on your machine?
The code uses the standard java.util.logging Logger, and the logger name is available at EventProcessorHost.EVENTPROCESSORHOST_TRACE. If you turn on logging with level FINE, you should see "Calling user-provided initial offset provider" and "Initial timestamp provided: xxxxxxx". If you see "Retrieved starting offset xxxx//yyyy" then it has found a checkpoint instead.

**Comment by PeterKelecom** [comment]
Ok, turns out it does find a checkpoint with offset -1. 

Did I mess up when I created the consumer group?

**Comment by JamesBirdsall** [comment]
No, consumer groups are a general Event Hub concept and checkpoints are particular to Event Processor Host. The only way to create a checkpoint is for user code in the event processor to call one of the PartitionContext.checkpoint() methods.
Right now there is no exposed way to delete a checkpoint, but if you create another consumer group, or use the EventProcessorHost constructor which takes a storage container name (to avoid using the existing storage container where the undesired checkpoints are), then you should avoid this problem.

**Comment by PeterKelecom** [comment]
this happens when I create a new consumergroup, without checkpointing, for every consumergroup I create.

**Comment by JamesBirdsall** [comment]
That was a valuable clue, thanks. It led me to discover that the default storage container name is being created from the event hub name only, which explains why those checkpoints are following you across consumer groups. I have opened issue 261 to fix the default container name to include the consumer group name.
Can you try using an EventProcessorHost constructor that lets you supply a storage container name? Ideally the container would not exist already, meaning no blobs in it, meaning no stray checkpoints, and then you should get the behavior you're expecting.

**Comment by PeterKelecom** [comment]
that did it, thanks!

**Comment by PeterKelecom** [comment]
Upon further testing, this only works the first time, when the container doesn't exist. After that, the container is created, contains a folder for the consumergroup and in that folder has checkpoint data, even though the processor never checkpoints. On restart of the processor, it starts processing messages from the start of the queue.

**Comment by JamesBirdsall** [comment]
Never mind issue 261, that turned out to be me being confused. When I changed my test case to do the stop and restart as you describe, I was able to reproduce your issue, and I found the code which was creating the unwanted checkpoints. I have created issue 262 and am testing a fix now.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#17

**Comment by sorenhoyer** [comment]
I ran into this issue just recently, where an existing storage container had some undesired checkpoints, but the solution is not very obvious for people new to azure event hub programming, and should perhaps a documented a little better. 

I still think it should be a possible to force ignore those existing checkpoints in code, and that it's a problem that "the initial offset provider is ignored in favor of a checkpoint for a partition". If you really want to favor checkpoints over explicitly stating InitialOffsetProvider in EventProcessorOptions then at least introduce another parameter for let us force InitialOffsetProvider over checkpoints. Or are there any good reasons not to give people control over this in code?
