### ISSUE TITLE
EPH checkpoint store initialization creating unwanted checkpoints with offset -1

### ISSUE THREAD

**Issue by JamesBirdsall** [Azure/azure-event-hubs#262]
It is legal to never create a checkpoint for a partition. Now that the initial offset provider supports timestamps, it can be a useful scenario to not have a checkpoint and just receive events by time. The checkpoint store initialization is creating unwanted checkpoints which interfere with that scenario.

**Comment by JamesBirdsall** [comment]
Fix pushed to javaEPH2

**Comment by PeterKelecom** [comment]
@JamesBirdsall I'll test it over the next few days

**Comment by JamesBirdsall** [comment]
Thanks! There was one more change that I pushed Tuesday afternoon. Please be sure to get that when you test.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#16
