### ISSUE TITLE
Event processor host consumers are not reliable 

### ISSUE THREAD

**Issue by mayuraviraj** [Azure/azure-event-hubs#271]
I'm using Event processing host to consume events in following way. But there are some issue with this consumer as data is not consumed reliably. 

Event processor creation code,

```
EventProcessorHost host = new EventProcessorHost(iotHubName,
	consumerGroup,
	iotHubMessageConnectionString,
	storageConnectionString);
EventProcessorOptions options = EventProcessorOptions.getDefaultOptions();
options.setExceptionNotification((errorArg) -> System.out.println("Host Name : " + errorArg.getHostname() + 
	" Action : " + errorArg.getAction() + ": Error :" + errorArg.getException()));
host.registerEventProcessorFactory(new MyFactory(), options).get();

// MyFactory
public class MyFactory implements IEventProcessorFactory {
    @Override
    public IEventProcessor createEventProcessor(PartitionContext partitionContext) throws Exception {
        return new MyProcessor();
    }
}

public class MyProcessor implements IEventProcessor {

    @Override
    public void onOpen(PartitionContext context) throws Exception {
       Sytem.out.println("Partition " +context.getPartitionId() + " onOpen");
    }

    @Override
    public void onClose(PartitionContext context, CloseReason reason) throws Exception {
       Sytem.out.println("Partition " +context.getPartitionId() + " onClose");
    }

    @Override
    public void onError(PartitionContext context, Throwable error) {
       Sytem.out.println("Partition " +context.getPartitionId() + "onError.");
    }

    @Override
    public void onEvents(PartitionContext context, Iterable<EventData> messages) throws Exception {
       Sytem.out.println("DATA " + messages.size());
    }
}
```

I'm using 0.8.1 version. 

My problem is above code work perfectly only for some time. At the starup consumer begin to consume events and there are no errors. But after some time ( like running after 5 or 6 hours) consumers stop consuming events. There are no errors in log but whatever I put into the event hub does not comes to consumers. Also I can see from the storage, lease for each partition is in fixed state ( I have 2 partitions). Lease blobs are not get updated. This problem is resolved once I restart the application.

**Comment by JamesBirdsall** [comment]
This is a known issue with 0.8.1. Can you please try it with 0.8.2 (both eventhub client and event processor host need to be updated at the same time)? Thanks!

**Comment by SreeramGarlapati** [comment]
possible dup of #254 
@mayuraviraj - please close if 0.8.2 fixes this problem.

**Comment by SreeramGarlapati** [comment]
Hello @mayuraviraj - here's are the change from 0.8.1 to 0.8.2: https://github.com/Azure/azure-event-hubs/blob/master/java/changelog.md

Please let us know if this recovers your current situation or this is a new issue..

**Comment by mayuraviraj** [comment]
0.8.2 version fixed the issue. Thanks for the help.
