### ISSUE TITLE
[C client]: Build fails (missing openssl dependencies)

### ISSUE THREAD

**Issue by bcraun** [Azure/azure-event-hubs#280]
**Steps followed:**

**1. git clone azure-event-hubs repo
2. Navigate to 'c' directory. then 'git submodule update --init --recursive'
3. Verify dependencies are pulled
4. Create a folder named "build" underneath the "c" directory
5. Run cmake ..
6. Build. The build process will vary by platform; for Linux the default is "make".**

```
<other build output>

[  8%] Built target uamqp
[  9%] Building C object azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o
/home/debian/azure-event-hubs/c/azure-uamqp-c/azure-c-shared-utility/c/src/tlsio_openssl.c:9:25: fatal error: openssl/ssl.h: No such file or directory
 #include "openssl/ssl.h"
                         ^
compilation terminated.
azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/build.make:878: recipe for target 'azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o' failed
make[2]: *** [azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1
CMakeFiles/Makefile2:153: recipe for target 'azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/all' failed
make[1]: *** [azure-uamqp-c/azure-c-shared-utility/c/CMakeFiles/aziotsharedutil.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Does "azure-shared-utility" need to be built first passing -Duse_openssl:bool=ON as well as setting an environment variable named "OpenSSLDir"? It's not clear from the readme in the c folder what order the dependencies are to be built.

### Please help this is a blocking issue!

**Comment by mrohera** [comment]
Hello bcraun,
Sorry for the delay in response but it looks like you have moved ahead and are unblocked. 

For the benefit of the community I would like to note that OpenSSL dependencies (curl, libcurl-openssl-dev and libssl-dev) and other dependencies have been called out in the c/build_all/Linux/setup.sh dir. Please tailor that script to your environment and obtain the relevant packages.

I will also call this out in the main README.md to avoid this situation.

Thank you for your patience.
