### ISSUE TITLE
JavaClient: Reactor thread is not a deamon thread and remans running after EventHubClient is closed

### ISSUE THREAD

**Issue by ialexandrov** [Azure/azure-event-hubs#283]
There is already an issue about unmanaged threads used in the JavaClient implementation.

java / azure-eventhubs / src / main / java / com / microsoft / azure / servicebus / MessagingFactory.java 

134         final Thread reactorThread = new Thread(new RunReactor(newReactor)); 
135         reactorThread.start(); 

Thread is started and then forgoten.  Later it prevents JVM from exiting.  This is even a bigger issue in the EE environment.
1. Please switch to using ExecutorService
2. Please shutdown the executor upon EventHubClient close

**Comment by SreeramGarlapati** [comment]
@ialexandrov - thanks a lot for filing this issue. I am fixing this... ETA 10/28

**Comment by SreeramGarlapati** [comment]
HI @ialexandrov - Thanks a lot for filing the issue. I am working on the
fix.

**Comment by SreeramGarlapati** [comment]
#287 fixes the daemon thread issue. Can you please validate... 

We will start taking ExecutorService in the Client API soon.

**Comment by SreeramGarlapati** [comment]
@ialexandrov - we released 0.9.0 - which addresses this issue. give it a try & let us know!

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#5
