### ISSUE TITLE
JavaClient: MessageSender and ReplayableWorkItem are not thread-dase but got accessed from various threads

### ISSUE THREAD

**Issue by ialexandrov** [Azure/azure-event-hubs#284]
MessageSender has set of fields which are not final.  At the same time methods of MessageSender are called from different threads without any state synchronization. This will lead to ocasional phantom isssues. 
Either make MessageSender thread safe or make sure all members of it are only accessed from reactor thread,

For example:
MessageSender.lastKnownLinkError is set by reactor thread in onError method and read in sendCore() method which is called from ForJoinPool due to (probably) bug in EventHubClient.send(..,) methods where **thenComposeAsync is called instead on thenCompose.**

More of less the same problem is with ReplayableWorkItem.lastKnownException which is again is set by reactor thread but read from timer thread pool thread:

java / azure-eventhubs / src / main / java / com / microsoft / azure / servicebus / MessageSender.java 
`778                    MessageSender.this.throwSenderTimeout(sendData.getWork(), sendData.getLastKnownException());`

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#4
