### ISSUE TITLE
Test issue 1

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs#285]

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#1

**Comment by SreeramGarlapati** [comment]
awesome.

**Comment by SreeramGarlapati** [comment]
@serkantkaraca / @jtaubensee - is there a way to move code in such a way that it retains history ?

**Comment by SreeramGarlapati** [comment]
and @jtaubensee - one important thing for us to find here is - if we can move label's and milestones and everything in them across git repo's (for javaclient & eph - we tried to label pretty much every issue).

**Comment by jtaubensee** [comment]
@SreeramGarlapati - Yes there is. We followed the same process for https://github.com/azure/azure-event-hubs-dotnet. Also notice that the history there is only relevant to that subfolder.

In regards to moving issues, so far it seems like there is an opensource tool to move them one at a time. So there is some manual overhead, but it worked well. I dont know that we will have all of the issues from a historical standpoint, but we will certainly get anything that is still open.

**Comment by SreeramGarlapati** [comment]
@jtaubensee - cool - what is that tool?
