### ISSUE TITLE
Release numbers are confusing

### ISSUE THREAD

**Issue by shpros** [Azure/azure-event-hubs#292]
As of this writing, [NPM](https://www.npmjs.com/package/azure-event-hubs) says `0.0.4 is the latest of 4 releases`, but the [releases](https://github.com/Azure/azure-event-hubs/releases) tab of this GitHub project says that `v0.8.0` is the most recent of 14 releases going back to `v0.3.0`. 

1. Why do the release numbers change so drastically between GitHub and NPM?
2. We are currently using NPM release 0.0.3 but ought to be moving to 0.0.4. So that we can determine what has changed, to which GitHub releases do the NPM releases 0.0.3 and 0.0.4 correspond?

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#3
