### ISSUE TITLE
nodemcu support

### ISSUE THREAD

**Issue by rishikeshayre1310** [Azure/azure-event-hubs#293]
hello 
Is it possible to connect esp8266nodemcu to Azure event hub.
 If so can anybody please guide me how to do it.
thank you

**Comment by rishikeshayre1310** [comment]
if anyone is looking for interfacing Nodemcu with Azure event Hub then check this link . I was able to implement the same.

http://stackoverflow.com/questions/40602293/is-it-possible-to-connect-nodemcu-with-microsoft-azure-event-hub

**Comment by jtaubensee** [comment]
Closing based on the provided link.
