### ISSUE TITLE
How to manage the offset on client side to read from the partition.

### ISSUE THREAD

**Issue by sngpt08** [Azure/azure-event-hubs#296]
i am using this api to get the data from eventHub EventHubReceiver_ReceiveFromStartTimestampAsync(eventHubReceiveHandle, OnReceiveCB, NULL, OnErrorCB, NULL,now);

here now = time(NULL);

i am storing json string in eventhub. but most of the time my application got crashed because i got some junk char in my json data. but if i change the startTimestamp value it works.

so whats the way to figure out the correct offset value ?

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-c#3
