### ISSUE TITLE
[Java-Azure-EventHub-Send-Issue] Not able to push messages to Event Hub

### ISSUE THREAD

**Issue by vedhera** [Azure/azure-event-hubs#298]
Hi,
I am using the following code to send messages to event hub and getting following error:

`com.microsoft.azure.servicebus.ServiceBusException: connection aborted`

`package com.adf.eventhub;

/**
 * Created by akhilesh on 15/2/17.
 */

import java.io.IOException;
import java.nio.charset.*;
import java.util.*;
import java.util.concurrent.ExecutionException;

import com.microsoft.azure.eventhubs.*;
import com.microsoft.azure.servicebus.*;

public class Send
{
    public static void main(String[] args)
            throws ServiceBusException, ExecutionException, InterruptedException, IOException {
        final String namespaceName = "mcdp-event-hub";
        final String eventHubName = "akhilesh-event-hub";
        final String sasKeyName = "mysendpolicy";
        final String sasKey = "<Key>";
        ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);

        byte[] payloadBytes = "Test AMQP message from JMS".getBytes("UTF-8");
        EventData sendEvent = new EventData(payloadBytes);

        EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
        ehClient.sendSync(sendEvent);
    }

}
`
Kindly suggest what is wrong in my implementation.

**Comment by vedhera** [comment]
I get this error everytime I run the code. Moreover I tried changing the dependency to 0.10.0 but still did not work.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#62
