### ISSUE TITLE
Common integrations

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs#303]
# Document common integrations
#### TOC Location 
* Under Overview
#### Abstract
Similar to common use cases (#302), we need to provide common integrations with other Azure Services:
* Azure Functions
* Stream Analytics
* IaaS VM

**Comment by jtaubensee** [comment]
Adding:
* API Management
* Azure Monitoring

**Comment by sethmanheim** [comment]
Stub article for experiment: https://github.com/Microsoft/azure-docs-pr/pull/9779.
