### ISSUE TITLE
Handling errors and retry

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs#305]
# Document best practices for handling errors and retry
#### TOC Location 
* How to -> Develop
#### Abstract
This article should cover:
* What different kinds are errors are there?
* What happens when I get an error?
* What kinds of errors should be retried? Which shouldn't?
* Custom retry policy

**Comment by ArunAdPushup** [comment]
By when can we expect this to be complete ?

**Comment by sethmanheim** [comment]
@ArunAdPushup When do you think you can give us the info?

**Comment by sethmanheim** [comment]
Stub article for experiment: https://github.com/Microsoft/azure-docs-pr/pull/9779.
