### ISSUE TITLE
JavaClient: EventData does not contained all amqp properties

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#31]
the EventData code only get the following from AmqpMessage:
- PartitionKey, SequenceNumber, EnqueuedTimeUtc from message annotation
- Application Properties

However it is not getting the AmqpMessage.Properties (the Amqp generic properties). This is actually needed in the IoT scenarios.

**Comment by hmlam** [comment]
by AmqpMessage.Properties I mean AmqpMessage.MessageAnnotations

**Comment by SreeramGarlapati** [comment]
@hmlam - should we stuff-in the MessageAnnotations in EventData.Properties?
In .net - we push them to EventData.SystemProperties - although these are not interpreted by the System (aka EventHubs service).

**Comment by SreeramGarlapati** [comment]
Hi @mzesriv - I fixed this issue here - please ack if you see that the fix is complete:

```
<repositories>
  <repository>  
            <id>azure eventhubs</id>  
            <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1284/</url>  
      </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-eventhubs</artifactId>
        <version>0.6.10</version>
    </dependency>
</dependencies>
```

**On a received EventData look in eventData.Properties map for all the additional properties (like DeviceID) added by IoTHub.**

**Comment by SreeramGarlapati** [comment]
This is fixed a-while-back.  @mzesri - please reopen if you see any problem.
