### ISSUE TITLE
REST API's missing

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs#310]
The new [REST API docs](https://docs.microsoft.com/rest/api/eventhub/), have two APIs missing:
* Get partition runtime metadata
* List partition runtime metadata

Also, the service name in the left pane is incorrect. It should be Event Hubs, not Event Hub.

![asdfasdf](https://cloud.githubusercontent.com/assets/8162917/23918248/758529b8-08af-11e7-8d0f-6c9d7019ee47.png)

 cc @sjkwak

**Comment by sethmanheim** [comment]
Under https://msdn.microsoft.com/en-us/library/azure/mt652156.aspx:

https://msdn.microsoft.com/en-us/library/azure/mt619971.aspx
https://msdn.microsoft.com/en-us/library/azure/mt619973.aspx

**Comment by sethmanheim** [comment]
Closing, moved API topics to docs.ms.com.
