### ISSUE TITLE
tx.send is not a function

### ISSUE THREAD

**Issue by ArunAdPushup** [Azure/azure-event-hubs#312]
Hi,

While trying to send data to eventhubs using ``azure-event-hubs`` package ``v0.0.7``, I am getting the following error - 

![screen shot 2017-04-04 at 4 00 42 pm](https://cloud.githubusercontent.com/assets/20511680/24652763/ad7fb868-1950-11e7-9a7a-8f846d53f23d.png)

Here's the code - 

```javascript
var EventHubClient = require('azure-event-hubs').Client;
 
var client = EventHubClient.fromConnectionString('Endpoint=sb://my-servicebus-namespace.servicebus.windows.net/;SharedAccessKeyName=my-SA-name;SharedAccessKey=my-SA-key', 'myeventhub')
client.open()
    .bind(client.createSender.bind(client))
    .then(function (tx) {
        tx.on('errorReceived', function (err) { console.log(err); });
        tx.send({ contents: 'Here is some text sent to partition key my-pk.' }, 'my-pk'); 
    });
```

I am following ``Example 3`` to create a sender, as shown [here](https://www.npmjs.com/package/azure-event-hubs#example-3---create-a-sender-v1).

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#22
