### ISSUE TITLE
Fix Microsoft.Azure.Management.EventHub Nuget Project Url

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-event-hubs#324]
The title says it all.

The Microsoft.Azure.Management.EventHub Nuget package points to Azure/AutoRest as its project URL.

**Comment by serkantkaraca** [comment]
This issue needs to be reported on https://github.com/Azure/azure-sdk-for-net

I am opening the same issue there. https://github.com/Azure/azure-sdk-for-net/issues/3526
