### ISSUE TITLE
REST API does not return NotFound

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-event-hubs#325]
I'm using the REST method for getting a hub, as documented here...

https://docs.microsoft.com/en-us/rest/api/eventhub/get-event-hub

If I pass in a valid hub, I get the data I would expect. If I pass in a hub that does not exist, I still get a 200 status code, and this content...

_"<feed xmlns="http://www.w3.org/2005/Atom"><title type="text">Publicly Listed Services</title><subtitle type="text">This is the list of publicly-listed services currently available.</subtitle><id>uuid:bac15d84-2363-40a9-a508-0c1a7edb9389;id=1078</id><updated>2017-07-18T20:48:27Z</updated><generator>Service Bus 1.1</generator></feed>"_

As this is a REST interface, I would expect to get a 404. Besides this issue, is there an easier way to confirm whether a hub exists or not? Also on the documentation page, the sample GET provides a ContentType header which doesn't make sense. Thanks.

**Comment by sjkwak** [comment]
Thanks for the reporting. This is a known issue and we are going to fix the issue in new version of REST APIs  that we're working on.
