### ISSUE TITLE
EventHub error led to meltdown in reactor 4

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-event-hubs#326]
Just trying to find out whether there's any point posting here, as issues can apparently be ignored for weeks.

**Comment by ShubhaVijayasarathy** [comment]
Sorry for this, will look into these.

**Comment by sabeegrewal** [comment]
Hey jackbond - we're in the process of disabling issues here actually. If you have issues specific to our client libraries, please open an issue there! You'll get a quick response there. 

If you have a service related issue, please open a ticket through the Azure portal!
