### ISSUE TITLE
[NodeJS] systemProperties is empty object in 0.0.8

### ISSUE THREAD

**Issue by ha62791** [Azure/azure-event-hubs#333]
Node version: 6.10.0
azure-event-hubs: 0.0.8

message.systemProperties is empty object in 0.0.8
It is not empty in 0.0.4

**Comment by sabeegrewal** [comment]
Please open an issue here: https://github.com/azure/azure-event-hubs-node! Sorry for the hold up - you'll get quick support there 👍
