### ISSUE TITLE
Event Hub receives empty events

### ISSUE THREAD

**Issue by Kapster17** [Azure/azure-event-hubs#343]
I initially posed the issue in the Azure functions forum.
https://github.com/Azure/Azure-Functions/issues/589

Azure event hub is receiving empty messages constantly. I checked all my publishes and am sure I am not publishing them. How do I know where are the message being published from ? I have a azure function trigger that prints nothing. C# Event Hub trigger function processed a message:

Even tried creating a new hub. This issue exist
EventHubTrigger-Shadow (, , cca2b799-b2c9- ...) |   | a minute ago | (0 ms) |  
-- | -- | -- | -- | --
EventHubTrigger-Shadow (, , 22ee5396-4366- ...) |   | 3 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 36291c1b-6068- ...) |   | 5 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , a6d1e881-0c73- ...) |   | 7 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , b231e89c-169b- ...) |   | 9 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 717364a8-5e10- ...) |   | 11 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , eaa094f7-7373- ...) |   | 13 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , c22987f0-7977- ...) |   | 15 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , dc2cf579-2ead- ...) |   | 17 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 4018f242-46d6- ...) |   | 19 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , e5355f06-ac82- ...) |   | 21 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 0f535e0d-9c50- ...) |   | 23 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 5eecab47-9e4e- ...) |   | 25 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , ba922374-0c3e- ...) |   | 27 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , ae2b6f9a-1162- ...) |   | 29 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 8fe792c0-1c76- ...) |   | 31 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , bad1f28f-0b01- ...) |   | 33 minutes ago | (0 ms) |  
EventHubTrigger-Shadow (, , 2b26a80b-d063- ...) |   | 35 minutes ago | (0 ms)

**Comment by ChristianWolf42** [comment]
@Kapster17 sorry for the late response. I looked a bit through the function thread, are you still seeing the same issue or did you find a solution already? 
If you have no solution yet, can you elaborate the data flow in your app?
Typically event hub is very reliable and should not materialize empty messages, hence I want to understand the communication flow a bit better in your case.

**Comment by ChristianWolf42** [comment]
Qualifying what I said above (unless you send the message empty...)

**Comment by Kapster17** [comment]
The flow is 
1- our IOT device sends messages to the IOT hub (We do not send Empty messages)
2- A Stream Job whose input is the IOT hub and Output is an eventhub processes all the messages.
3- An Azure function is triggered for event in the eventHub.

We do not send empty messages. My concern here is the Empty events which causes my Azure function to be called.

**Comment by ChristianWolf42** [comment]
@Kapster17 Did you also open a support ticket? I have a ticket number which sounds remarkably similar than your description.

**Comment by Kapster17** [comment]
Yes....just did that .

**Comment by ChristianWolf42** [comment]
Ok, let us follow through on the support channel...
