### ISSUE TITLE
Incorrect name of constant used in .NET Core receiver sample

### ISSUE THREAD

**Issue by reeceaw** [Azure/azure-event-hubs#355]
# Azure Event Hubs Issue Creation
A constant is referenced that does not exist due to incorrect naming in the .NET Core receiver sample:

<img width="626" alt="screen shot 2018-01-18 at 15 47 28" src="https://user-images.githubusercontent.com/17890560/35106779-09b33818-fc67-11e7-80ba-87d7ce54613d.png">

**Comment by serkantkaraca** [comment]
Thx for reporting this. Fix is merged.
