### ISSUE TITLE
'TokenProvider' does not contain a definition for 'CreateManagedServiceIdentityTokenProvider'

### ISSUE THREAD

**Issue by mtuppad** [Azure/azure-event-hubs#358]
## Actual Behavior
1. when I download https://github.com/Azure/azure-event-hubs/tree/master/samples/DotNet/MSI/EventHubsMSIDemoWebApp  and build, I get the below errors.
I have updated Visual studio ad nugget packages. Tried on VS2017 Community and Enterprise edition same issues.

Which version do I need to use.  

\samples\DotNet\MSI\EventHubsMSIDemoWebApp\EventHubsMSIDemoWebApp\EventHubsMSIDemo.aspx.cs(27,47,27,88): error CS0117: 'TokenProvider' does not contain a definition for 'CreateManagedServiceIdentityTokenProvider'

\samples\DotNet\MSI\EventHubsMSIDemoWebApp\EventHubsMSIDemoWebApp\EventHubsMSIDemo.aspx.cs(27,89,27,104): error CS0103: The name 'ServiceAudience' does not exist in the current context

\samples\DotNet\MSI\EventHubsMSIDemoWebApp\EventHubsMSIDemoWebApp\EventHubsMSIDemo.aspx.cs(44,47,44,88): error CS0117: 'TokenProvider' does not contain a definition for 'CreateManagedServiceIdentityTokenProvider'

\samples\DotNet\MSI\EventHubsMSIDemoWebApp\EventHubsMSIDemoWebApp\EventHubsMSIDemo.aspx.cs(44,89,44,104): error CS0103: The name 'ServiceAudience' does not exist in the current context

## Expected Behavior
1. 
2.

**Comment by mtuppad** [comment]
Can someone help me?

**Comment by serkantkaraca** [comment]
Please import this Nuget package: https://www.nuget.org/packages/WindowsAzure.ServiceBus/4.2.1-preview

**Comment by mtuppad** [comment]
Thanks That worked.
