### ISSUE TITLE
Unable to receive events when Secure transfer required is enabled in blob storage

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [Azure/azure-event-hubs#365]
# Azure Event Hubs Issue Creation

## Actual Behavior
1. we have migrated Classic storage to ARM storage and enabled Secure transfer data option.In Blob we will store consumer information.
2. After migration event hub stops working we are not getting any exception.Event sender is sending event but receiver not receiving.

## Expected Behavior
1. It should work as previoulsy event if we enable secure transfer data
2.

**Comment by abdulrahaman7** [comment]
Issue is related to storage connection, we are using DefaultEndpointsProtocol as http even after enabling secure transfer enabled configuration. After updating DefaultEndpointsProtocol to https it working fine.
