### ISSUE TITLE
Limitiations on consumer group count

### ISSUE THREAD

**Issue by denisulmer** [Azure/azure-event-hubs#366]
Why is the number of consumer groups limited to 20 per EH?

## Actual Behavior
1.  Consumer Groups are limited to 20 per Event Hub 

## Expected Behavior
1. Ability to create more than 20 Consumer Groups

**Comment by serkantkaraca** [comment]
You can still contact Azure Support and ask for a limit increase by providing business justification. It is really rare seeing a customer asking for more than 20 consumer groups thus not provided as self-service.

**Comment by denisulmer** [comment]
Sure, but the limit seems to be very arbitrary. The consumer group is only a string as all the handling is happening in the blob storage anyway.

**Comment by sabeegrewal** [comment]
Hey @denisulmer we limit the consumer group to prevent abuse of the service. If you think our limit should be raised (without contacting support), please create an idea here: https://feedback.azure.com/forums/34192--general-feedback
