### ISSUE TITLE
Not able to receive events from specified offset in all partitions

### ISSUE THREAD

**Issue by vyshaliN** [Azure/azure-event-hubs#369]
I'm using createEpochReceiver function of azure-eventhubs java sdk to receive events in Spark .Based on the number of partitions of EventHubs,I'm using the following pseudocode to collect eventhubs data in parallel

val rdd = sparkSession.sparkContext.parallelize(Seq("0","1","2")) //Based on the number of partitions,an RDD[String] is created

val eventHubsData = rdd.mapPartition(partitionRecords => {
               var events = new List[EventData]()
partitionRecords.foreach(partitionId => {
            //creating a receiver for each partition
            ehClient.createEpochReceiver(EventHubClient.DEFAULT_CONSUMER_GROUP_NAME, partitionId, <offset-value>,false 1).get()
                               
             //receive events for particular partition
             Iterable<EventData> receivedEvents = receiver.receive(100).get();

             //add the received events to the list
             receivedEvents.foreach(record => events.add(eventdata))
})
//return the list
events.listiterator
})
The problem is that the list holds only one event having the offset next to the specifed offset here.
Not sure what is the problem in retrieving all the events from the specified offset.

P.S Using 0.15.1 version of azure-eventhubs sdk

**Comment by sjkwak** [comment]
Hi @vyshaliN, the behavior is expected as the receive call returns events as soon as they are delivered from the service. So, for the scenario that you described, application will need to keep calling receive until all the events in a partition are retrieved. Please note that the library prefetch events and receive call will return as many events as possible while not exceeding max count.

By the way, have you tried Event Hubs connector for Spark? If not, please check https://github.com/Azure/azure-event-hubs-spark site and document - https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/structured-streaming-eventhubs-integration.md
