### ISSUE TITLE
EventProcessorHost - Event processors not being registered after switching to "Premium Performance" storage account

### ISSUE THREAD

**Issue by tobiasb** [Azure/azure-event-hubs#374]
_I opened [#260](https://github.com/Azure/azure-event-hubs-dotnet/issues/260) but was asked to create an issue here instead_

## Actual Behavior
1. Event processors not being registered

## Expected Behavior
1. Event processors are registered

We are using the `EventProcessorHost` to process messages from an EventHub. The event processor host requires a storage account for the coordination of event processors. After changing the storage account to use I'm having an issue where the event processors are not being registered anymore.

I verified it is a storage account related issue by creating another storage account with different configuration and it works. With the "bad" storage account, the `EventProcessorHost.RegisterEventProcessorFactoryAsync` is called successfully, yet the factory's `CreateEventProcessor` is never called. No exception is being thrown.

The only difference I could find between the "good" and the "bad" storage account is that the "bad" one is on a "Premium" performance plan whereas the "good" one is on a "Standard" performance plan.

There is evidence that the connection to the storage account is successful in principle because I can see that the blob container with the name of the event hub being created in the storage account.

## Versions  
- OS platform and version: Windows 10/Windows Server 2016 (Azure VM)
- .NET Version: 4.6.1
- NuGet package version or commit ID: 
WindowsAzure.ServiceBus 4.1.8
WindowsAzure.Storage 9.1.0

**Comment by sabeegrewal** [comment]
Hey @tobiasb, 

So, I just got the team to agree to disable issues on this repo - it doesn't seem like a good place to track issues. For client issues, we have our corresponding repos (**except for Full .NET which you are using**) and we have the Azure protal to file support tickets. 

With that said, for the last time, could you please [file this again through the Azure portal](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request)?

I want to make sure you get help, so if for some reason that isn't working, you can contact me via [this repo](https://github.com/Azure/azure-event-hubs-spark) - I actively manage that repo. If you reach out there, I can help you get a support ticket filed!
