### ISSUE TITLE
JavaClient: How do user "abort" a client?

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#38]
In .Net we have Abort() because user want to have a predictable "cleanup" method - one that does not throw exception and is deterministic in time. E.g. A lot of times user process is healthy but just need a quick way to reset before quitting that process

We should consider if Java world need such a concept. Currently looks like user will have to do their own abort logic (call close(), catch all exceptions, have a timer that quits if close takes too long)

**Comment by sjkwak** [comment]
We will need more feedback from customers about whether this feature is needed.
