### ISSUE TITLE
JavaClient: Class naming not consistent between senders and receivers

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#41]
We have EventHubSender but PartitionReceiver. So we have a couple of problems here:

- EventHubSender should be called PartitionSender (I see we only exposes this for partition sending).
- PartitionRecevier may have a name clash in future when we have messaging added in. Make sure in Java namespace is a good way to separate same classes from different feature.

**Comment by SreeramGarlapati** [comment]
We fixed this to have PartitionSender & PartitionReceiver. Thanks!
