### ISSUE TITLE
JavaClient: ClientEntity should have both close() and closeSync()

### ISSUE THREAD

**Issue by hmlam** [Azure/azure-event-hubs#54]
couple of fit and finish problem here.

1. ClientEntity.closeAsync should actually be call close() (assuming we follow the convention of close() actually is the async method).
2. ClientEntity should have a closeSync() method that do close in sync style because...
3. we have EventHubClient.close() and EventHubClient.closeAsync() that actually do the same thing, but I am guessing the intent was to have close() and closeSync() instead?

**Comment by SreeramGarlapati** [comment]
This was fixed as part of commit#b1d3d3b3f7e88ee2007fc00fa052ed4edb6e0def. Thanks!
