### ISSUE TITLE
Using Publisher Policy SAS in send sample

### ISSUE THREAD

**Issue by cbaekdorf** [Azure/azure-event-hubs#6]
How can I use Publisher Policy SAS key (giving each device a unique connection string) in the send.c sample (https://github.com/Azure/azure-event-hubs/tree/master/c/eventhub_client/samples/send)?

When using the Shared Access Key the connection string looks like “Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=SendAccess;SharedAccessKey=<my key>”, but how should the connection string look like if using a Publisher Policy SAS key with a publisher id?

I know how to do it using .NET library, but cannot figure out how to get it working with the C sample. I tried “Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessSignature=SharedAccessSignature sr=sb%3a%2f%2fmy-namespace.servicebus.windows.net%2fmy-hub%2fpublishers%2fmyPublisherId&sig=<my sas key>&se=1445431507&skn=FullAccess;EntityPath=device-data-input-sample;Publisher=myPublisherId”, but that gives EVENTHUBCLIENT_INVALID_ARG.

In .NET I can use this "Endpoint=sb://mynamespace.servicebus.windows.net/;SharedAccessSignature=SharedAccessSignature sr=sb%3a%2f%2fmynamespace.servicebus.windows.net%2fmyinput%2fpublishers%2fdevice0000&sig=L4EIURzEV6Oxh.....12wYxFnsEzmo%3d&se=1445503693&skn=Send;EntityPath=myinput;Publisher=device0000;TransportType=Amqp;AmqpSecurityScheme=cbs" with the EventHubSender.CreateFromConnectionString(connectionString) but that is not working with the C code send.c sample.

**Comment by dcristoloveanu** [comment]
This will be added soon (next thing on the feature list).

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-c#2
