### ISSUE TITLE
"Azure Eventhub Client for C" samples links are broken

### ISSUE THREAD

**Issue by BretStateham** [Azure/azure-event-hubs#86]
The links to the "samples" folder, and the various platform samples (Beaglebone Black, Fedora Linux, Ubuntu Linux, etc.) are broken on the https://github.com/Azure/azure-event-hubs/blob/master/c/README.md.  Looks like they have all moved to the "docs" folder https://github.com/Azure/azure-event-hubs/tree/master/c/docs

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-c#1
