### ISSUE TITLE
JavaClient: javaEPH Branch

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/azure-event-hubs#89]
Just curious when the javaEPH branch will be merged into master

**Comment by JamesBirdsall** [comment]
It's going to be several more weeks. We're getting close to code complete for EventProcessorHost, but then it needs to be tested extensively before it's ready to be official. When it can run for several days at full blast without leaking/blowing up/etc., then it will be golden. :)

**Comment by jhosteny** [comment]
@JamesBirdsall Any estimate on release? We are evaluating Event Hubs and have to decide rather soon if we need to pick an alternate.

**Comment by JamesBirdsall** [comment]
EPH has been delayed a couple times -- I was gone for most of April, and since I got back most of the available testing resources have gone to stabilizing the underlying Java EH client. We are now reaching the point of doing real testing on EPH, and I'm hoping it will drop in early June.

**Comment by dcieslak19973** [comment]
@JamesBirdsall - Early June approaches. Is there anything I can do to help ensure this merges soon?

**Comment by hmlam** [comment]
This is now done via https://github.com/Azure/azure-event-hubs/pull/171
